# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import common_cmd_pb2 as common__cmd__pb2


class CommonCMDServiceStub(object):
    """定义服务（RPC接口）
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetIDN = channel.unary_unary(
                '/silicon_based.CommonCMDService/GetIDN',
                request_serializer=common__cmd__pb2.GetIDNRequest.SerializeToString,
                response_deserializer=common__cmd__pb2.GetIDNResponse.FromString,
                _registered_method=True)
        self.GetDeviceInfo = channel.unary_unary(
                '/silicon_based.CommonCMDService/GetDeviceInfo',
                request_serializer=common__cmd__pb2.GetDeviceInfoRequest.SerializeToString,
                response_deserializer=common__cmd__pb2.GetDeviceInfoResponse.FromString,
                _registered_method=True)
        self.SetDebugParam = channel.unary_unary(
                '/silicon_based.CommonCMDService/SetDebugParam',
                request_serializer=common__cmd__pb2.DebugParamRequest.SerializeToString,
                response_deserializer=common__cmd__pb2.ParamResponse.FromString,
                _registered_method=True)
        self.SetGPIOStatus = channel.unary_unary(
                '/silicon_based.CommonCMDService/SetGPIOStatus',
                request_serializer=common__cmd__pb2.GPIOStatusRequest.SerializeToString,
                response_deserializer=common__cmd__pb2.ParamResponse.FromString,
                _registered_method=True)
        self.SetNetCfgAddr = channel.unary_unary(
                '/silicon_based.CommonCMDService/SetNetCfgAddr',
                request_serializer=common__cmd__pb2.SetNetCfgRequest.SerializeToString,
                response_deserializer=common__cmd__pb2.ParamResponse.FromString,
                _registered_method=True)
        self.GetNetCfgAddr = channel.unary_unary(
                '/silicon_based.CommonCMDService/GetNetCfgAddr',
                request_serializer=common__cmd__pb2.GetNetCfgRequest.SerializeToString,
                response_deserializer=common__cmd__pb2.NetCfgResponse.FromString,
                _registered_method=True)
        self.SetRegValue = channel.unary_unary(
                '/silicon_based.CommonCMDService/SetRegValue',
                request_serializer=common__cmd__pb2.RegSetRequest.SerializeToString,
                response_deserializer=common__cmd__pb2.ParamResponse.FromString,
                _registered_method=True)
        self.GetRegValue = channel.unary_unary(
                '/silicon_based.CommonCMDService/GetRegValue',
                request_serializer=common__cmd__pb2.RegGetRequest.SerializeToString,
                response_deserializer=common__cmd__pb2.RegValueResponse.FromString,
                _registered_method=True)
        self.SetPCIERegValue = channel.unary_unary(
                '/silicon_based.CommonCMDService/SetPCIERegValue',
                request_serializer=common__cmd__pb2.PCIERegSetRequest.SerializeToString,
                response_deserializer=common__cmd__pb2.ParamResponse.FromString,
                _registered_method=True)
        self.GetPCIERegValue = channel.unary_unary(
                '/silicon_based.CommonCMDService/GetPCIERegValue',
                request_serializer=common__cmd__pb2.PCIERegGetRequest.SerializeToString,
                response_deserializer=common__cmd__pb2.PCIERegValueResponse.FromString,
                _registered_method=True)
        self.StreamDataSet = channel.stream_unary(
                '/silicon_based.CommonCMDService/StreamDataSet',
                request_serializer=common__cmd__pb2.SetStreamDataRequest.SerializeToString,
                response_deserializer=common__cmd__pb2.SetStreamResult.FromString,
                _registered_method=True)
        self.StreamDataGet = channel.unary_stream(
                '/silicon_based.CommonCMDService/StreamDataGet',
                request_serializer=common__cmd__pb2.GetStreamDataRequest.SerializeToString,
                response_deserializer=common__cmd__pb2.GetStreamResult.FromString,
                _registered_method=True)
        self.SetDevTrigSource = channel.unary_unary(
                '/silicon_based.CommonCMDService/SetDevTrigSource',
                request_serializer=common__cmd__pb2.SetTrigSourceRequest.SerializeToString,
                response_deserializer=common__cmd__pb2.ParamResponse.FromString,
                _registered_method=True)
        self.GetDevTrigSource = channel.unary_unary(
                '/silicon_based.CommonCMDService/GetDevTrigSource',
                request_serializer=common__cmd__pb2.GetTrigSourceRequest.SerializeToString,
                response_deserializer=common__cmd__pb2.GetTrigSourceResponse.FromString,
                _registered_method=True)
        self.SetDevTrigParam = channel.unary_unary(
                '/silicon_based.CommonCMDService/SetDevTrigParam',
                request_serializer=common__cmd__pb2.SetTrigParamRequest.SerializeToString,
                response_deserializer=common__cmd__pb2.ParamResponse.FromString,
                _registered_method=True)
        self.GetDevTrigParam = channel.unary_unary(
                '/silicon_based.CommonCMDService/GetDevTrigParam',
                request_serializer=common__cmd__pb2.GetTrigParamRequest.SerializeToString,
                response_deserializer=common__cmd__pb2.GetTrigParamResponse.FromString,
                _registered_method=True)
        self.SetTrigStart = channel.unary_unary(
                '/silicon_based.CommonCMDService/SetTrigStart',
                request_serializer=common__cmd__pb2.SetTrigStartRequest.SerializeToString,
                response_deserializer=common__cmd__pb2.ParamResponse.FromString,
                _registered_method=True)
        self.SetRERIOFeadbackTest = channel.unary_unary(
                '/silicon_based.CommonCMDService/SetRERIOFeadbackTest',
                request_serializer=common__cmd__pb2.SetRERIOFeadbackTestRequest.SerializeToString,
                response_deserializer=common__cmd__pb2.ParamResponse.FromString,
                _registered_method=True)
        self.GetRERIOFeadbackTest = channel.unary_unary(
                '/silicon_based.CommonCMDService/GetRERIOFeadbackTest',
                request_serializer=common__cmd__pb2.GetRERIOFeadbackTestRequest.SerializeToString,
                response_deserializer=common__cmd__pb2.GetRERIOFeadbackTestResponse.FromString,
                _registered_method=True)


class CommonCMDServiceServicer(object):
    """定义服务（RPC接口）
    """

    def GetIDN(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetDeviceInfo(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetDebugParam(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetGPIOStatus(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetNetCfgAddr(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetNetCfgAddr(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetRegValue(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetRegValue(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetPCIERegValue(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetPCIERegValue(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StreamDataSet(self, request_iterator, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StreamDataGet(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetDevTrigSource(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetDevTrigSource(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetDevTrigParam(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetDevTrigParam(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetTrigStart(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetRERIOFeadbackTest(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetRERIOFeadbackTest(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_CommonCMDServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetIDN': grpc.unary_unary_rpc_method_handler(
                    servicer.GetIDN,
                    request_deserializer=common__cmd__pb2.GetIDNRequest.FromString,
                    response_serializer=common__cmd__pb2.GetIDNResponse.SerializeToString,
            ),
            'GetDeviceInfo': grpc.unary_unary_rpc_method_handler(
                    servicer.GetDeviceInfo,
                    request_deserializer=common__cmd__pb2.GetDeviceInfoRequest.FromString,
                    response_serializer=common__cmd__pb2.GetDeviceInfoResponse.SerializeToString,
            ),
            'SetDebugParam': grpc.unary_unary_rpc_method_handler(
                    servicer.SetDebugParam,
                    request_deserializer=common__cmd__pb2.DebugParamRequest.FromString,
                    response_serializer=common__cmd__pb2.ParamResponse.SerializeToString,
            ),
            'SetGPIOStatus': grpc.unary_unary_rpc_method_handler(
                    servicer.SetGPIOStatus,
                    request_deserializer=common__cmd__pb2.GPIOStatusRequest.FromString,
                    response_serializer=common__cmd__pb2.ParamResponse.SerializeToString,
            ),
            'SetNetCfgAddr': grpc.unary_unary_rpc_method_handler(
                    servicer.SetNetCfgAddr,
                    request_deserializer=common__cmd__pb2.SetNetCfgRequest.FromString,
                    response_serializer=common__cmd__pb2.ParamResponse.SerializeToString,
            ),
            'GetNetCfgAddr': grpc.unary_unary_rpc_method_handler(
                    servicer.GetNetCfgAddr,
                    request_deserializer=common__cmd__pb2.GetNetCfgRequest.FromString,
                    response_serializer=common__cmd__pb2.NetCfgResponse.SerializeToString,
            ),
            'SetRegValue': grpc.unary_unary_rpc_method_handler(
                    servicer.SetRegValue,
                    request_deserializer=common__cmd__pb2.RegSetRequest.FromString,
                    response_serializer=common__cmd__pb2.ParamResponse.SerializeToString,
            ),
            'GetRegValue': grpc.unary_unary_rpc_method_handler(
                    servicer.GetRegValue,
                    request_deserializer=common__cmd__pb2.RegGetRequest.FromString,
                    response_serializer=common__cmd__pb2.RegValueResponse.SerializeToString,
            ),
            'SetPCIERegValue': grpc.unary_unary_rpc_method_handler(
                    servicer.SetPCIERegValue,
                    request_deserializer=common__cmd__pb2.PCIERegSetRequest.FromString,
                    response_serializer=common__cmd__pb2.ParamResponse.SerializeToString,
            ),
            'GetPCIERegValue': grpc.unary_unary_rpc_method_handler(
                    servicer.GetPCIERegValue,
                    request_deserializer=common__cmd__pb2.PCIERegGetRequest.FromString,
                    response_serializer=common__cmd__pb2.PCIERegValueResponse.SerializeToString,
            ),
            'StreamDataSet': grpc.stream_unary_rpc_method_handler(
                    servicer.StreamDataSet,
                    request_deserializer=common__cmd__pb2.SetStreamDataRequest.FromString,
                    response_serializer=common__cmd__pb2.SetStreamResult.SerializeToString,
            ),
            'StreamDataGet': grpc.unary_stream_rpc_method_handler(
                    servicer.StreamDataGet,
                    request_deserializer=common__cmd__pb2.GetStreamDataRequest.FromString,
                    response_serializer=common__cmd__pb2.GetStreamResult.SerializeToString,
            ),
            'SetDevTrigSource': grpc.unary_unary_rpc_method_handler(
                    servicer.SetDevTrigSource,
                    request_deserializer=common__cmd__pb2.SetTrigSourceRequest.FromString,
                    response_serializer=common__cmd__pb2.ParamResponse.SerializeToString,
            ),
            'GetDevTrigSource': grpc.unary_unary_rpc_method_handler(
                    servicer.GetDevTrigSource,
                    request_deserializer=common__cmd__pb2.GetTrigSourceRequest.FromString,
                    response_serializer=common__cmd__pb2.GetTrigSourceResponse.SerializeToString,
            ),
            'SetDevTrigParam': grpc.unary_unary_rpc_method_handler(
                    servicer.SetDevTrigParam,
                    request_deserializer=common__cmd__pb2.SetTrigParamRequest.FromString,
                    response_serializer=common__cmd__pb2.ParamResponse.SerializeToString,
            ),
            'GetDevTrigParam': grpc.unary_unary_rpc_method_handler(
                    servicer.GetDevTrigParam,
                    request_deserializer=common__cmd__pb2.GetTrigParamRequest.FromString,
                    response_serializer=common__cmd__pb2.GetTrigParamResponse.SerializeToString,
            ),
            'SetTrigStart': grpc.unary_unary_rpc_method_handler(
                    servicer.SetTrigStart,
                    request_deserializer=common__cmd__pb2.SetTrigStartRequest.FromString,
                    response_serializer=common__cmd__pb2.ParamResponse.SerializeToString,
            ),
            'SetRERIOFeadbackTest': grpc.unary_unary_rpc_method_handler(
                    servicer.SetRERIOFeadbackTest,
                    request_deserializer=common__cmd__pb2.SetRERIOFeadbackTestRequest.FromString,
                    response_serializer=common__cmd__pb2.ParamResponse.SerializeToString,
            ),
            'GetRERIOFeadbackTest': grpc.unary_unary_rpc_method_handler(
                    servicer.GetRERIOFeadbackTest,
                    request_deserializer=common__cmd__pb2.GetRERIOFeadbackTestRequest.FromString,
                    response_serializer=common__cmd__pb2.GetRERIOFeadbackTestResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'silicon_based.CommonCMDService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('silicon_based.CommonCMDService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class CommonCMDService(object):
    """定义服务（RPC接口）
    """

    @staticmethod
    def GetIDN(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/silicon_based.CommonCMDService/GetIDN',
            common__cmd__pb2.GetIDNRequest.SerializeToString,
            common__cmd__pb2.GetIDNResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetDeviceInfo(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/silicon_based.CommonCMDService/GetDeviceInfo',
            common__cmd__pb2.GetDeviceInfoRequest.SerializeToString,
            common__cmd__pb2.GetDeviceInfoResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SetDebugParam(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/silicon_based.CommonCMDService/SetDebugParam',
            common__cmd__pb2.DebugParamRequest.SerializeToString,
            common__cmd__pb2.ParamResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SetGPIOStatus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/silicon_based.CommonCMDService/SetGPIOStatus',
            common__cmd__pb2.GPIOStatusRequest.SerializeToString,
            common__cmd__pb2.ParamResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SetNetCfgAddr(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/silicon_based.CommonCMDService/SetNetCfgAddr',
            common__cmd__pb2.SetNetCfgRequest.SerializeToString,
            common__cmd__pb2.ParamResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetNetCfgAddr(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/silicon_based.CommonCMDService/GetNetCfgAddr',
            common__cmd__pb2.GetNetCfgRequest.SerializeToString,
            common__cmd__pb2.NetCfgResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SetRegValue(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/silicon_based.CommonCMDService/SetRegValue',
            common__cmd__pb2.RegSetRequest.SerializeToString,
            common__cmd__pb2.ParamResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetRegValue(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/silicon_based.CommonCMDService/GetRegValue',
            common__cmd__pb2.RegGetRequest.SerializeToString,
            common__cmd__pb2.RegValueResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SetPCIERegValue(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/silicon_based.CommonCMDService/SetPCIERegValue',
            common__cmd__pb2.PCIERegSetRequest.SerializeToString,
            common__cmd__pb2.ParamResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetPCIERegValue(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/silicon_based.CommonCMDService/GetPCIERegValue',
            common__cmd__pb2.PCIERegGetRequest.SerializeToString,
            common__cmd__pb2.PCIERegValueResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StreamDataSet(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_unary(
            request_iterator,
            target,
            '/silicon_based.CommonCMDService/StreamDataSet',
            common__cmd__pb2.SetStreamDataRequest.SerializeToString,
            common__cmd__pb2.SetStreamResult.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StreamDataGet(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/silicon_based.CommonCMDService/StreamDataGet',
            common__cmd__pb2.GetStreamDataRequest.SerializeToString,
            common__cmd__pb2.GetStreamResult.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SetDevTrigSource(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/silicon_based.CommonCMDService/SetDevTrigSource',
            common__cmd__pb2.SetTrigSourceRequest.SerializeToString,
            common__cmd__pb2.ParamResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetDevTrigSource(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/silicon_based.CommonCMDService/GetDevTrigSource',
            common__cmd__pb2.GetTrigSourceRequest.SerializeToString,
            common__cmd__pb2.GetTrigSourceResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SetDevTrigParam(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/silicon_based.CommonCMDService/SetDevTrigParam',
            common__cmd__pb2.SetTrigParamRequest.SerializeToString,
            common__cmd__pb2.ParamResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetDevTrigParam(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/silicon_based.CommonCMDService/GetDevTrigParam',
            common__cmd__pb2.GetTrigParamRequest.SerializeToString,
            common__cmd__pb2.GetTrigParamResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SetTrigStart(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/silicon_based.CommonCMDService/SetTrigStart',
            common__cmd__pb2.SetTrigStartRequest.SerializeToString,
            common__cmd__pb2.ParamResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SetRERIOFeadbackTest(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/silicon_based.CommonCMDService/SetRERIOFeadbackTest',
            common__cmd__pb2.SetRERIOFeadbackTestRequest.SerializeToString,
            common__cmd__pb2.ParamResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetRERIOFeadbackTest(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/silicon_based.CommonCMDService/GetRERIOFeadbackTest',
            common__cmd__pb2.GetRERIOFeadbackTestRequest.SerializeToString,
            common__cmd__pb2.GetRERIOFeadbackTestResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
