# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import common_cmd_pb2 as common__cmd__pb2
import lnawg_cmd_pb2 as lnawg__cmd__pb2


class LNAWGCMDServiceStub(object):
    """定义服务（RPC接口）
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.SetMode = channel.unary_unary(
                '/silicon_based.LNAWGCMDService/SetMode',
                request_serializer=lnawg__cmd__pb2.ModeSetRequest.SerializeToString,
                response_deserializer=common__cmd__pb2.ParamResponse.FromString,
                )
        self.GetMode = channel.unary_unary(
                '/silicon_based.LNAWGCMDService/GetMode',
                request_serializer=lnawg__cmd__pb2.ModeGetRequest.SerializeToString,
                response_deserializer=lnawg__cmd__pb2.ModeGetResponse.FromString,
                )
        self.SetRun = channel.unary_unary(
                '/silicon_based.LNAWGCMDService/SetRun',
                request_serializer=lnawg__cmd__pb2.RunSetRequest.SerializeToString,
                response_deserializer=common__cmd__pb2.ParamResponse.FromString,
                )
        self.GetRun = channel.unary_unary(
                '/silicon_based.LNAWGCMDService/GetRun',
                request_serializer=lnawg__cmd__pb2.RunGetRequest.SerializeToString,
                response_deserializer=lnawg__cmd__pb2.RunGetResponse.FromString,
                )
        self.SetExtSource = channel.unary_unary(
                '/silicon_based.LNAWGCMDService/SetExtSource',
                request_serializer=lnawg__cmd__pb2.ExtSourceSetRequest.SerializeToString,
                response_deserializer=common__cmd__pb2.ParamResponse.FromString,
                )
        self.GetExtSource = channel.unary_unary(
                '/silicon_based.LNAWGCMDService/GetExtSource',
                request_serializer=lnawg__cmd__pb2.ExtSourceGetRequest.SerializeToString,
                response_deserializer=lnawg__cmd__pb2.ExtSourceGetResponse.FromString,
                )
        self.SetRange = channel.unary_unary(
                '/silicon_based.LNAWGCMDService/SetRange',
                request_serializer=lnawg__cmd__pb2.RangeSetRequest.SerializeToString,
                response_deserializer=common__cmd__pb2.ParamResponse.FromString,
                )
        self.GetRange = channel.unary_unary(
                '/silicon_based.LNAWGCMDService/GetRange',
                request_serializer=lnawg__cmd__pb2.RangeGetRequest.SerializeToString,
                response_deserializer=lnawg__cmd__pb2.RangeGetResponse.FromString,
                )
        self.SetOffset = channel.unary_unary(
                '/silicon_based.LNAWGCMDService/SetOffset',
                request_serializer=lnawg__cmd__pb2.OffsetSetRequest.SerializeToString,
                response_deserializer=common__cmd__pb2.ParamResponse.FromString,
                )
        self.GetOffset = channel.unary_unary(
                '/silicon_based.LNAWGCMDService/GetOffset',
                request_serializer=lnawg__cmd__pb2.OffsetGetRequest.SerializeToString,
                response_deserializer=lnawg__cmd__pb2.OffsetGetResponse.FromString,
                )
        self.SetSegmentCount = channel.unary_unary(
                '/silicon_based.LNAWGCMDService/SetSegmentCount',
                request_serializer=lnawg__cmd__pb2.SegmentCountSetRequest.SerializeToString,
                response_deserializer=common__cmd__pb2.ParamResponse.FromString,
                )
        self.GetSegmentCount = channel.unary_unary(
                '/silicon_based.LNAWGCMDService/GetSegmentCount',
                request_serializer=lnawg__cmd__pb2.SegmentCountGetRequest.SerializeToString,
                response_deserializer=lnawg__cmd__pb2.SegmentCountGetResponse.FromString,
                )
        self.SetLoopCount = channel.unary_unary(
                '/silicon_based.LNAWGCMDService/SetLoopCount',
                request_serializer=lnawg__cmd__pb2.LoopCountSetRequest.SerializeToString,
                response_deserializer=common__cmd__pb2.ParamResponse.FromString,
                )
        self.GetLoopCount = channel.unary_unary(
                '/silicon_based.LNAWGCMDService/GetLoopCount',
                request_serializer=lnawg__cmd__pb2.LoopCountGetRequest.SerializeToString,
                response_deserializer=lnawg__cmd__pb2.LoopCountGetResponse.FromString,
                )
        self.SetDDSParam = channel.unary_unary(
                '/silicon_based.LNAWGCMDService/SetDDSParam',
                request_serializer=lnawg__cmd__pb2.DDSParamSetRequest.SerializeToString,
                response_deserializer=common__cmd__pb2.ParamResponse.FromString,
                )
        self.GetDDSParam = channel.unary_unary(
                '/silicon_based.LNAWGCMDService/GetDDSParam',
                request_serializer=lnawg__cmd__pb2.DDSParamGetRequest.SerializeToString,
                response_deserializer=lnawg__cmd__pb2.DDSParamGetResponse.FromString,
                )
        self.SetChirpOutParam = channel.unary_unary(
                '/silicon_based.LNAWGCMDService/SetChirpOutParam',
                request_serializer=lnawg__cmd__pb2.ChirpOutParamSetRequest.SerializeToString,
                response_deserializer=common__cmd__pb2.ParamResponse.FromString,
                )
        self.GetChirpOutParam = channel.unary_unary(
                '/silicon_based.LNAWGCMDService/GetChirpOutParam',
                request_serializer=lnawg__cmd__pb2.ChirpOutParamGetRequest.SerializeToString,
                response_deserializer=lnawg__cmd__pb2.ChirpOutParamGetResponse.FromString,
                )
        self.SetDDSEnable = channel.unary_unary(
                '/silicon_based.LNAWGCMDService/SetDDSEnable',
                request_serializer=lnawg__cmd__pb2.DDSEnableSetRequest.SerializeToString,
                response_deserializer=common__cmd__pb2.ParamResponse.FromString,
                )
        self.GetDDSEnable = channel.unary_unary(
                '/silicon_based.LNAWGCMDService/GetDDSEnable',
                request_serializer=lnawg__cmd__pb2.DDSEnableGetRequest.SerializeToString,
                response_deserializer=lnawg__cmd__pb2.DDSEnableGetResponse.FromString,
                )


class LNAWGCMDServiceServicer(object):
    """定义服务（RPC接口）
    """

    def SetMode(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetMode(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetRun(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetRun(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetExtSource(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetExtSource(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetRange(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetRange(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetOffset(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetOffset(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetSegmentCount(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetSegmentCount(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetLoopCount(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetLoopCount(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetDDSParam(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetDDSParam(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetChirpOutParam(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetChirpOutParam(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetDDSEnable(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetDDSEnable(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_LNAWGCMDServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'SetMode': grpc.unary_unary_rpc_method_handler(
                    servicer.SetMode,
                    request_deserializer=lnawg__cmd__pb2.ModeSetRequest.FromString,
                    response_serializer=common__cmd__pb2.ParamResponse.SerializeToString,
            ),
            'GetMode': grpc.unary_unary_rpc_method_handler(
                    servicer.GetMode,
                    request_deserializer=lnawg__cmd__pb2.ModeGetRequest.FromString,
                    response_serializer=lnawg__cmd__pb2.ModeGetResponse.SerializeToString,
            ),
            'SetRun': grpc.unary_unary_rpc_method_handler(
                    servicer.SetRun,
                    request_deserializer=lnawg__cmd__pb2.RunSetRequest.FromString,
                    response_serializer=common__cmd__pb2.ParamResponse.SerializeToString,
            ),
            'GetRun': grpc.unary_unary_rpc_method_handler(
                    servicer.GetRun,
                    request_deserializer=lnawg__cmd__pb2.RunGetRequest.FromString,
                    response_serializer=lnawg__cmd__pb2.RunGetResponse.SerializeToString,
            ),
            'SetExtSource': grpc.unary_unary_rpc_method_handler(
                    servicer.SetExtSource,
                    request_deserializer=lnawg__cmd__pb2.ExtSourceSetRequest.FromString,
                    response_serializer=common__cmd__pb2.ParamResponse.SerializeToString,
            ),
            'GetExtSource': grpc.unary_unary_rpc_method_handler(
                    servicer.GetExtSource,
                    request_deserializer=lnawg__cmd__pb2.ExtSourceGetRequest.FromString,
                    response_serializer=lnawg__cmd__pb2.ExtSourceGetResponse.SerializeToString,
            ),
            'SetRange': grpc.unary_unary_rpc_method_handler(
                    servicer.SetRange,
                    request_deserializer=lnawg__cmd__pb2.RangeSetRequest.FromString,
                    response_serializer=common__cmd__pb2.ParamResponse.SerializeToString,
            ),
            'GetRange': grpc.unary_unary_rpc_method_handler(
                    servicer.GetRange,
                    request_deserializer=lnawg__cmd__pb2.RangeGetRequest.FromString,
                    response_serializer=lnawg__cmd__pb2.RangeGetResponse.SerializeToString,
            ),
            'SetOffset': grpc.unary_unary_rpc_method_handler(
                    servicer.SetOffset,
                    request_deserializer=lnawg__cmd__pb2.OffsetSetRequest.FromString,
                    response_serializer=common__cmd__pb2.ParamResponse.SerializeToString,
            ),
            'GetOffset': grpc.unary_unary_rpc_method_handler(
                    servicer.GetOffset,
                    request_deserializer=lnawg__cmd__pb2.OffsetGetRequest.FromString,
                    response_serializer=lnawg__cmd__pb2.OffsetGetResponse.SerializeToString,
            ),
            'SetSegmentCount': grpc.unary_unary_rpc_method_handler(
                    servicer.SetSegmentCount,
                    request_deserializer=lnawg__cmd__pb2.SegmentCountSetRequest.FromString,
                    response_serializer=common__cmd__pb2.ParamResponse.SerializeToString,
            ),
            'GetSegmentCount': grpc.unary_unary_rpc_method_handler(
                    servicer.GetSegmentCount,
                    request_deserializer=lnawg__cmd__pb2.SegmentCountGetRequest.FromString,
                    response_serializer=lnawg__cmd__pb2.SegmentCountGetResponse.SerializeToString,
            ),
            'SetLoopCount': grpc.unary_unary_rpc_method_handler(
                    servicer.SetLoopCount,
                    request_deserializer=lnawg__cmd__pb2.LoopCountSetRequest.FromString,
                    response_serializer=common__cmd__pb2.ParamResponse.SerializeToString,
            ),
            'GetLoopCount': grpc.unary_unary_rpc_method_handler(
                    servicer.GetLoopCount,
                    request_deserializer=lnawg__cmd__pb2.LoopCountGetRequest.FromString,
                    response_serializer=lnawg__cmd__pb2.LoopCountGetResponse.SerializeToString,
            ),
            'SetDDSParam': grpc.unary_unary_rpc_method_handler(
                    servicer.SetDDSParam,
                    request_deserializer=lnawg__cmd__pb2.DDSParamSetRequest.FromString,
                    response_serializer=common__cmd__pb2.ParamResponse.SerializeToString,
            ),
            'GetDDSParam': grpc.unary_unary_rpc_method_handler(
                    servicer.GetDDSParam,
                    request_deserializer=lnawg__cmd__pb2.DDSParamGetRequest.FromString,
                    response_serializer=lnawg__cmd__pb2.DDSParamGetResponse.SerializeToString,
            ),
            'SetChirpOutParam': grpc.unary_unary_rpc_method_handler(
                    servicer.SetChirpOutParam,
                    request_deserializer=lnawg__cmd__pb2.ChirpOutParamSetRequest.FromString,
                    response_serializer=common__cmd__pb2.ParamResponse.SerializeToString,
            ),
            'GetChirpOutParam': grpc.unary_unary_rpc_method_handler(
                    servicer.GetChirpOutParam,
                    request_deserializer=lnawg__cmd__pb2.ChirpOutParamGetRequest.FromString,
                    response_serializer=lnawg__cmd__pb2.ChirpOutParamGetResponse.SerializeToString,
            ),
            'SetDDSEnable': grpc.unary_unary_rpc_method_handler(
                    servicer.SetDDSEnable,
                    request_deserializer=lnawg__cmd__pb2.DDSEnableSetRequest.FromString,
                    response_serializer=common__cmd__pb2.ParamResponse.SerializeToString,
            ),
            'GetDDSEnable': grpc.unary_unary_rpc_method_handler(
                    servicer.GetDDSEnable,
                    request_deserializer=lnawg__cmd__pb2.DDSEnableGetRequest.FromString,
                    response_serializer=lnawg__cmd__pb2.DDSEnableGetResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'silicon_based.LNAWGCMDService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class LNAWGCMDService(object):
    """定义服务（RPC接口）
    """

    @staticmethod
    def SetMode(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/silicon_based.LNAWGCMDService/SetMode',
            lnawg__cmd__pb2.ModeSetRequest.SerializeToString,
            common__cmd__pb2.ParamResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetMode(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/silicon_based.LNAWGCMDService/GetMode',
            lnawg__cmd__pb2.ModeGetRequest.SerializeToString,
            lnawg__cmd__pb2.ModeGetResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def SetRun(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/silicon_based.LNAWGCMDService/SetRun',
            lnawg__cmd__pb2.RunSetRequest.SerializeToString,
            common__cmd__pb2.ParamResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetRun(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/silicon_based.LNAWGCMDService/GetRun',
            lnawg__cmd__pb2.RunGetRequest.SerializeToString,
            lnawg__cmd__pb2.RunGetResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def SetExtSource(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/silicon_based.LNAWGCMDService/SetExtSource',
            lnawg__cmd__pb2.ExtSourceSetRequest.SerializeToString,
            common__cmd__pb2.ParamResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetExtSource(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/silicon_based.LNAWGCMDService/GetExtSource',
            lnawg__cmd__pb2.ExtSourceGetRequest.SerializeToString,
            lnawg__cmd__pb2.ExtSourceGetResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def SetRange(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/silicon_based.LNAWGCMDService/SetRange',
            lnawg__cmd__pb2.RangeSetRequest.SerializeToString,
            common__cmd__pb2.ParamResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetRange(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/silicon_based.LNAWGCMDService/GetRange',
            lnawg__cmd__pb2.RangeGetRequest.SerializeToString,
            lnawg__cmd__pb2.RangeGetResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def SetOffset(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/silicon_based.LNAWGCMDService/SetOffset',
            lnawg__cmd__pb2.OffsetSetRequest.SerializeToString,
            common__cmd__pb2.ParamResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetOffset(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/silicon_based.LNAWGCMDService/GetOffset',
            lnawg__cmd__pb2.OffsetGetRequest.SerializeToString,
            lnawg__cmd__pb2.OffsetGetResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def SetSegmentCount(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/silicon_based.LNAWGCMDService/SetSegmentCount',
            lnawg__cmd__pb2.SegmentCountSetRequest.SerializeToString,
            common__cmd__pb2.ParamResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetSegmentCount(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/silicon_based.LNAWGCMDService/GetSegmentCount',
            lnawg__cmd__pb2.SegmentCountGetRequest.SerializeToString,
            lnawg__cmd__pb2.SegmentCountGetResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def SetLoopCount(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/silicon_based.LNAWGCMDService/SetLoopCount',
            lnawg__cmd__pb2.LoopCountSetRequest.SerializeToString,
            common__cmd__pb2.ParamResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetLoopCount(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/silicon_based.LNAWGCMDService/GetLoopCount',
            lnawg__cmd__pb2.LoopCountGetRequest.SerializeToString,
            lnawg__cmd__pb2.LoopCountGetResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def SetDDSParam(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/silicon_based.LNAWGCMDService/SetDDSParam',
            lnawg__cmd__pb2.DDSParamSetRequest.SerializeToString,
            common__cmd__pb2.ParamResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetDDSParam(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/silicon_based.LNAWGCMDService/GetDDSParam',
            lnawg__cmd__pb2.DDSParamGetRequest.SerializeToString,
            lnawg__cmd__pb2.DDSParamGetResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def SetChirpOutParam(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/silicon_based.LNAWGCMDService/SetChirpOutParam',
            lnawg__cmd__pb2.ChirpOutParamSetRequest.SerializeToString,
            common__cmd__pb2.ParamResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetChirpOutParam(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/silicon_based.LNAWGCMDService/GetChirpOutParam',
            lnawg__cmd__pb2.ChirpOutParamGetRequest.SerializeToString,
            lnawg__cmd__pb2.ChirpOutParamGetResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def SetDDSEnable(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/silicon_based.LNAWGCMDService/SetDDSEnable',
            lnawg__cmd__pb2.DDSEnableSetRequest.SerializeToString,
            common__cmd__pb2.ParamResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetDDSEnable(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/silicon_based.LNAWGCMDService/GetDDSEnable',
            lnawg__cmd__pb2.DDSEnableGetRequest.SerializeToString,
            lnawg__cmd__pb2.DDSEnableGetResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
