# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import common_cmd_pb2 as common__cmd__pb2
import qa_cmd_pb2 as qa__cmd__pb2


class QACMDServiceStub(object):
    """定义服务（RPC接口）
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.SetTrigSour = channel.unary_unary(
                '/silicon_based.QACMDService/SetTrigSour',
                request_serializer=qa__cmd__pb2.SetTrigSourRequest.SerializeToString,
                response_deserializer=common__cmd__pb2.ParamResponse.FromString,
                )
        self.SetSoftTrig = channel.unary_unary(
                '/silicon_based.QACMDService/SetSoftTrig',
                request_serializer=qa__cmd__pb2.SetSoftTrigRequest.SerializeToString,
                response_deserializer=common__cmd__pb2.ParamResponse.FromString,
                )
        self.SetDACDDSConfig = channel.unary_unary(
                '/silicon_based.QACMDService/SetDACDDSConfig',
                request_serializer=qa__cmd__pb2.SetDACDDSConfigRequest.SerializeToString,
                response_deserializer=common__cmd__pb2.ParamResponse.FromString,
                )
        self.GetDACDDSConfig = channel.unary_unary(
                '/silicon_based.QACMDService/GetDACDDSConfig',
                request_serializer=qa__cmd__pb2.GetDACDDSConfigRequest.SerializeToString,
                response_deserializer=qa__cmd__pb2.GetDACDDSConfigResponse.FromString,
                )
        self.SetDACPlayParam = channel.unary_unary(
                '/silicon_based.QACMDService/SetDACPlayParam',
                request_serializer=qa__cmd__pb2.SetDACPlayParamRequest.SerializeToString,
                response_deserializer=common__cmd__pb2.ParamResponse.FromString,
                )
        self.GetDACPlayParam = channel.unary_unary(
                '/silicon_based.QACMDService/GetDACPlayParam',
                request_serializer=qa__cmd__pb2.GetDACPlayParamRequest.SerializeToString,
                response_deserializer=qa__cmd__pb2.GetDACPlayParamResponse.FromString,
                )
        self.SetDACStartStop = channel.unary_unary(
                '/silicon_based.QACMDService/SetDACStartStop',
                request_serializer=qa__cmd__pb2.SetDACStartStopRequest.SerializeToString,
                response_deserializer=common__cmd__pb2.ParamResponse.FromString,
                )
        self.GetDACStartStop = channel.unary_unary(
                '/silicon_based.QACMDService/GetDACStartStop',
                request_serializer=qa__cmd__pb2.GetDACStartStopRequest.SerializeToString,
                response_deserializer=qa__cmd__pb2.GetDACStartStopResponse.FromString,
                )
        self.SetSampleParam = channel.unary_unary(
                '/silicon_based.QACMDService/SetSampleParam',
                request_serializer=qa__cmd__pb2.SetSampleParamRequest.SerializeToString,
                response_deserializer=common__cmd__pb2.ParamResponse.FromString,
                )
        self.GetSampleParam = channel.unary_unary(
                '/silicon_based.QACMDService/GetSampleParam',
                request_serializer=qa__cmd__pb2.GetSampleParamRequest.SerializeToString,
                response_deserializer=qa__cmd__pb2.GetSampleParamResponse.FromString,
                )
        self.SetSampleStartStop = channel.unary_unary(
                '/silicon_based.QACMDService/SetSampleStartStop',
                request_serializer=qa__cmd__pb2.SetSampleStartStopRequest.SerializeToString,
                response_deserializer=common__cmd__pb2.ParamResponse.FromString,
                )
        self.GetSampleStartStop = channel.unary_unary(
                '/silicon_based.QACMDService/GetSampleStartStop',
                request_serializer=qa__cmd__pb2.GetSampleStartStopRequest.SerializeToString,
                response_deserializer=qa__cmd__pb2.GetSampleStartStopResponse.FromString,
                )
        self.SetADCConfig = channel.unary_unary(
                '/silicon_based.QACMDService/SetADCConfig',
                request_serializer=qa__cmd__pb2.SetADCConfigRequest.SerializeToString,
                response_deserializer=common__cmd__pb2.ParamResponse.FromString,
                )
        self.GetADCConfig = channel.unary_unary(
                '/silicon_based.QACMDService/GetADCConfig',
                request_serializer=qa__cmd__pb2.GetADCConfigRequest.SerializeToString,
                response_deserializer=qa__cmd__pb2.GetADCConfigResponse.FromString,
                )
        self.SetADCPlayParam = channel.unary_unary(
                '/silicon_based.QACMDService/SetADCPlayParam',
                request_serializer=qa__cmd__pb2.SetADCPlayParamRequest.SerializeToString,
                response_deserializer=common__cmd__pb2.ParamResponse.FromString,
                )
        self.GetADCPlayParam = channel.unary_unary(
                '/silicon_based.QACMDService/GetADCPlayParam',
                request_serializer=qa__cmd__pb2.GetADCPlayParamRequest.SerializeToString,
                response_deserializer=qa__cmd__pb2.GetADCPlayParamResponse.FromString,
                )
        self.SetADCStartStop = channel.unary_unary(
                '/silicon_based.QACMDService/SetADCStartStop',
                request_serializer=qa__cmd__pb2.SetADCStartStopRequest.SerializeToString,
                response_deserializer=common__cmd__pb2.ParamResponse.FromString,
                )
        self.GetADCStartStop = channel.unary_unary(
                '/silicon_based.QACMDService/GetADCStartStop',
                request_serializer=qa__cmd__pb2.GetADCStartStopRequest.SerializeToString,
                response_deserializer=qa__cmd__pb2.GetADCStartStopResponse.FromString,
                )


class QACMDServiceServicer(object):
    """定义服务（RPC接口）
    """

    def SetTrigSour(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetSoftTrig(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetDACDDSConfig(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetDACDDSConfig(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetDACPlayParam(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetDACPlayParam(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetDACStartStop(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetDACStartStop(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetSampleParam(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetSampleParam(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetSampleStartStop(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetSampleStartStop(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetADCConfig(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetADCConfig(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetADCPlayParam(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetADCPlayParam(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetADCStartStop(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetADCStartStop(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_QACMDServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'SetTrigSour': grpc.unary_unary_rpc_method_handler(
                    servicer.SetTrigSour,
                    request_deserializer=qa__cmd__pb2.SetTrigSourRequest.FromString,
                    response_serializer=common__cmd__pb2.ParamResponse.SerializeToString,
            ),
            'SetSoftTrig': grpc.unary_unary_rpc_method_handler(
                    servicer.SetSoftTrig,
                    request_deserializer=qa__cmd__pb2.SetSoftTrigRequest.FromString,
                    response_serializer=common__cmd__pb2.ParamResponse.SerializeToString,
            ),
            'SetDACDDSConfig': grpc.unary_unary_rpc_method_handler(
                    servicer.SetDACDDSConfig,
                    request_deserializer=qa__cmd__pb2.SetDACDDSConfigRequest.FromString,
                    response_serializer=common__cmd__pb2.ParamResponse.SerializeToString,
            ),
            'GetDACDDSConfig': grpc.unary_unary_rpc_method_handler(
                    servicer.GetDACDDSConfig,
                    request_deserializer=qa__cmd__pb2.GetDACDDSConfigRequest.FromString,
                    response_serializer=qa__cmd__pb2.GetDACDDSConfigResponse.SerializeToString,
            ),
            'SetDACPlayParam': grpc.unary_unary_rpc_method_handler(
                    servicer.SetDACPlayParam,
                    request_deserializer=qa__cmd__pb2.SetDACPlayParamRequest.FromString,
                    response_serializer=common__cmd__pb2.ParamResponse.SerializeToString,
            ),
            'GetDACPlayParam': grpc.unary_unary_rpc_method_handler(
                    servicer.GetDACPlayParam,
                    request_deserializer=qa__cmd__pb2.GetDACPlayParamRequest.FromString,
                    response_serializer=qa__cmd__pb2.GetDACPlayParamResponse.SerializeToString,
            ),
            'SetDACStartStop': grpc.unary_unary_rpc_method_handler(
                    servicer.SetDACStartStop,
                    request_deserializer=qa__cmd__pb2.SetDACStartStopRequest.FromString,
                    response_serializer=common__cmd__pb2.ParamResponse.SerializeToString,
            ),
            'GetDACStartStop': grpc.unary_unary_rpc_method_handler(
                    servicer.GetDACStartStop,
                    request_deserializer=qa__cmd__pb2.GetDACStartStopRequest.FromString,
                    response_serializer=qa__cmd__pb2.GetDACStartStopResponse.SerializeToString,
            ),
            'SetSampleParam': grpc.unary_unary_rpc_method_handler(
                    servicer.SetSampleParam,
                    request_deserializer=qa__cmd__pb2.SetSampleParamRequest.FromString,
                    response_serializer=common__cmd__pb2.ParamResponse.SerializeToString,
            ),
            'GetSampleParam': grpc.unary_unary_rpc_method_handler(
                    servicer.GetSampleParam,
                    request_deserializer=qa__cmd__pb2.GetSampleParamRequest.FromString,
                    response_serializer=qa__cmd__pb2.GetSampleParamResponse.SerializeToString,
            ),
            'SetSampleStartStop': grpc.unary_unary_rpc_method_handler(
                    servicer.SetSampleStartStop,
                    request_deserializer=qa__cmd__pb2.SetSampleStartStopRequest.FromString,
                    response_serializer=common__cmd__pb2.ParamResponse.SerializeToString,
            ),
            'GetSampleStartStop': grpc.unary_unary_rpc_method_handler(
                    servicer.GetSampleStartStop,
                    request_deserializer=qa__cmd__pb2.GetSampleStartStopRequest.FromString,
                    response_serializer=qa__cmd__pb2.GetSampleStartStopResponse.SerializeToString,
            ),
            'SetADCConfig': grpc.unary_unary_rpc_method_handler(
                    servicer.SetADCConfig,
                    request_deserializer=qa__cmd__pb2.SetADCConfigRequest.FromString,
                    response_serializer=common__cmd__pb2.ParamResponse.SerializeToString,
            ),
            'GetADCConfig': grpc.unary_unary_rpc_method_handler(
                    servicer.GetADCConfig,
                    request_deserializer=qa__cmd__pb2.GetADCConfigRequest.FromString,
                    response_serializer=qa__cmd__pb2.GetADCConfigResponse.SerializeToString,
            ),
            'SetADCPlayParam': grpc.unary_unary_rpc_method_handler(
                    servicer.SetADCPlayParam,
                    request_deserializer=qa__cmd__pb2.SetADCPlayParamRequest.FromString,
                    response_serializer=common__cmd__pb2.ParamResponse.SerializeToString,
            ),
            'GetADCPlayParam': grpc.unary_unary_rpc_method_handler(
                    servicer.GetADCPlayParam,
                    request_deserializer=qa__cmd__pb2.GetADCPlayParamRequest.FromString,
                    response_serializer=qa__cmd__pb2.GetADCPlayParamResponse.SerializeToString,
            ),
            'SetADCStartStop': grpc.unary_unary_rpc_method_handler(
                    servicer.SetADCStartStop,
                    request_deserializer=qa__cmd__pb2.SetADCStartStopRequest.FromString,
                    response_serializer=common__cmd__pb2.ParamResponse.SerializeToString,
            ),
            'GetADCStartStop': grpc.unary_unary_rpc_method_handler(
                    servicer.GetADCStartStop,
                    request_deserializer=qa__cmd__pb2.GetADCStartStopRequest.FromString,
                    response_serializer=qa__cmd__pb2.GetADCStartStopResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'silicon_based.QACMDService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class QACMDService(object):
    """定义服务（RPC接口）
    """

    @staticmethod
    def SetTrigSour(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/silicon_based.QACMDService/SetTrigSour',
            qa__cmd__pb2.SetTrigSourRequest.SerializeToString,
            common__cmd__pb2.ParamResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def SetSoftTrig(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/silicon_based.QACMDService/SetSoftTrig',
            qa__cmd__pb2.SetSoftTrigRequest.SerializeToString,
            common__cmd__pb2.ParamResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def SetDACDDSConfig(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/silicon_based.QACMDService/SetDACDDSConfig',
            qa__cmd__pb2.SetDACDDSConfigRequest.SerializeToString,
            common__cmd__pb2.ParamResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetDACDDSConfig(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/silicon_based.QACMDService/GetDACDDSConfig',
            qa__cmd__pb2.GetDACDDSConfigRequest.SerializeToString,
            qa__cmd__pb2.GetDACDDSConfigResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def SetDACPlayParam(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/silicon_based.QACMDService/SetDACPlayParam',
            qa__cmd__pb2.SetDACPlayParamRequest.SerializeToString,
            common__cmd__pb2.ParamResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetDACPlayParam(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/silicon_based.QACMDService/GetDACPlayParam',
            qa__cmd__pb2.GetDACPlayParamRequest.SerializeToString,
            qa__cmd__pb2.GetDACPlayParamResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def SetDACStartStop(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/silicon_based.QACMDService/SetDACStartStop',
            qa__cmd__pb2.SetDACStartStopRequest.SerializeToString,
            common__cmd__pb2.ParamResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetDACStartStop(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/silicon_based.QACMDService/GetDACStartStop',
            qa__cmd__pb2.GetDACStartStopRequest.SerializeToString,
            qa__cmd__pb2.GetDACStartStopResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def SetSampleParam(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/silicon_based.QACMDService/SetSampleParam',
            qa__cmd__pb2.SetSampleParamRequest.SerializeToString,
            common__cmd__pb2.ParamResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetSampleParam(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/silicon_based.QACMDService/GetSampleParam',
            qa__cmd__pb2.GetSampleParamRequest.SerializeToString,
            qa__cmd__pb2.GetSampleParamResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def SetSampleStartStop(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/silicon_based.QACMDService/SetSampleStartStop',
            qa__cmd__pb2.SetSampleStartStopRequest.SerializeToString,
            common__cmd__pb2.ParamResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetSampleStartStop(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/silicon_based.QACMDService/GetSampleStartStop',
            qa__cmd__pb2.GetSampleStartStopRequest.SerializeToString,
            qa__cmd__pb2.GetSampleStartStopResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def SetADCConfig(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/silicon_based.QACMDService/SetADCConfig',
            qa__cmd__pb2.SetADCConfigRequest.SerializeToString,
            common__cmd__pb2.ParamResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetADCConfig(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/silicon_based.QACMDService/GetADCConfig',
            qa__cmd__pb2.GetADCConfigRequest.SerializeToString,
            qa__cmd__pb2.GetADCConfigResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def SetADCPlayParam(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/silicon_based.QACMDService/SetADCPlayParam',
            qa__cmd__pb2.SetADCPlayParamRequest.SerializeToString,
            common__cmd__pb2.ParamResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetADCPlayParam(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/silicon_based.QACMDService/GetADCPlayParam',
            qa__cmd__pb2.GetADCPlayParamRequest.SerializeToString,
            qa__cmd__pb2.GetADCPlayParamResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def SetADCStartStop(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/silicon_based.QACMDService/SetADCStartStop',
            qa__cmd__pb2.SetADCStartStopRequest.SerializeToString,
            common__cmd__pb2.ParamResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetADCStartStop(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/silicon_based.QACMDService/GetADCStartStop',
            qa__cmd__pb2.GetADCStartStopRequest.SerializeToString,
            qa__cmd__pb2.GetADCStartStopResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
