// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: common_cmd.proto

#include "common_cmd.pb.h"
#include "common_cmd.grpc.pb.h"

#include <functional>
#include <grpcpp/support/async_stream.h>
#include <grpcpp/support/async_unary_call.h>
#include <grpcpp/impl/channel_interface.h>
#include <grpcpp/impl/client_unary_call.h>
#include <grpcpp/support/client_callback.h>
#include <grpcpp/support/message_allocator.h>
#include <grpcpp/support/method_handler.h>
#include <grpcpp/impl/rpc_service_method.h>
#include <grpcpp/support/server_callback.h>
#include <grpcpp/impl/server_callback_handlers.h>
#include <grpcpp/server_context.h>
#include <grpcpp/impl/service_type.h>
#include <grpcpp/support/sync_stream.h>
namespace silicon_based {

static const char* CommonCMDService_method_names[] = {
  "/silicon_based.CommonCMDService/GetIDN",
  "/silicon_based.CommonCMDService/GetDeviceInfo",
  "/silicon_based.CommonCMDService/SetDebugParam",
  "/silicon_based.CommonCMDService/SetGPIOStatus",
  "/silicon_based.CommonCMDService/SetNetCfgAddr",
  "/silicon_based.CommonCMDService/GetNetCfgAddr",
  "/silicon_based.CommonCMDService/SetRegValue",
  "/silicon_based.CommonCMDService/GetRegValue",
  "/silicon_based.CommonCMDService/SetPCIERegValue",
  "/silicon_based.CommonCMDService/GetPCIERegValue",
  "/silicon_based.CommonCMDService/StreamDataSet",
  "/silicon_based.CommonCMDService/StreamDataGet",
  "/silicon_based.CommonCMDService/SetDevTrigSource",
  "/silicon_based.CommonCMDService/GetDevTrigSource",
  "/silicon_based.CommonCMDService/SetDevTrigParam",
  "/silicon_based.CommonCMDService/GetDevTrigParam",
  "/silicon_based.CommonCMDService/SetTrigStart",
  "/silicon_based.CommonCMDService/SetRERIOFeadbackTest",
  "/silicon_based.CommonCMDService/GetRERIOFeadbackTest",
};

std::unique_ptr< CommonCMDService::Stub> CommonCMDService::NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options) {
  (void)options;
  std::unique_ptr< CommonCMDService::Stub> stub(new CommonCMDService::Stub(channel, options));
  return stub;
}

CommonCMDService::Stub::Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options)
  : channel_(channel), rpcmethod_GetIDN_(CommonCMDService_method_names[0], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_GetDeviceInfo_(CommonCMDService_method_names[1], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_SetDebugParam_(CommonCMDService_method_names[2], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_SetGPIOStatus_(CommonCMDService_method_names[3], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_SetNetCfgAddr_(CommonCMDService_method_names[4], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_GetNetCfgAddr_(CommonCMDService_method_names[5], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_SetRegValue_(CommonCMDService_method_names[6], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_GetRegValue_(CommonCMDService_method_names[7], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_SetPCIERegValue_(CommonCMDService_method_names[8], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_GetPCIERegValue_(CommonCMDService_method_names[9], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_StreamDataSet_(CommonCMDService_method_names[10], options.suffix_for_stats(),::grpc::internal::RpcMethod::CLIENT_STREAMING, channel)
  , rpcmethod_StreamDataGet_(CommonCMDService_method_names[11], options.suffix_for_stats(),::grpc::internal::RpcMethod::SERVER_STREAMING, channel)
  , rpcmethod_SetDevTrigSource_(CommonCMDService_method_names[12], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_GetDevTrigSource_(CommonCMDService_method_names[13], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_SetDevTrigParam_(CommonCMDService_method_names[14], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_GetDevTrigParam_(CommonCMDService_method_names[15], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_SetTrigStart_(CommonCMDService_method_names[16], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_SetRERIOFeadbackTest_(CommonCMDService_method_names[17], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_GetRERIOFeadbackTest_(CommonCMDService_method_names[18], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  {}

::grpc::Status CommonCMDService::Stub::GetIDN(::grpc::ClientContext* context, const ::silicon_based::GetIDNRequest& request, ::silicon_based::GetIDNResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::silicon_based::GetIDNRequest, ::silicon_based::GetIDNResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_GetIDN_, context, request, response);
}

void CommonCMDService::Stub::async::GetIDN(::grpc::ClientContext* context, const ::silicon_based::GetIDNRequest* request, ::silicon_based::GetIDNResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::silicon_based::GetIDNRequest, ::silicon_based::GetIDNResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_GetIDN_, context, request, response, std::move(f));
}

void CommonCMDService::Stub::async::GetIDN(::grpc::ClientContext* context, const ::silicon_based::GetIDNRequest* request, ::silicon_based::GetIDNResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_GetIDN_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::silicon_based::GetIDNResponse>* CommonCMDService::Stub::PrepareAsyncGetIDNRaw(::grpc::ClientContext* context, const ::silicon_based::GetIDNRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::silicon_based::GetIDNResponse, ::silicon_based::GetIDNRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_GetIDN_, context, request);
}

::grpc::ClientAsyncResponseReader< ::silicon_based::GetIDNResponse>* CommonCMDService::Stub::AsyncGetIDNRaw(::grpc::ClientContext* context, const ::silicon_based::GetIDNRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncGetIDNRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status CommonCMDService::Stub::GetDeviceInfo(::grpc::ClientContext* context, const ::silicon_based::GetDeviceInfoRequest& request, ::silicon_based::GetDeviceInfoResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::silicon_based::GetDeviceInfoRequest, ::silicon_based::GetDeviceInfoResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_GetDeviceInfo_, context, request, response);
}

void CommonCMDService::Stub::async::GetDeviceInfo(::grpc::ClientContext* context, const ::silicon_based::GetDeviceInfoRequest* request, ::silicon_based::GetDeviceInfoResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::silicon_based::GetDeviceInfoRequest, ::silicon_based::GetDeviceInfoResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_GetDeviceInfo_, context, request, response, std::move(f));
}

void CommonCMDService::Stub::async::GetDeviceInfo(::grpc::ClientContext* context, const ::silicon_based::GetDeviceInfoRequest* request, ::silicon_based::GetDeviceInfoResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_GetDeviceInfo_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::silicon_based::GetDeviceInfoResponse>* CommonCMDService::Stub::PrepareAsyncGetDeviceInfoRaw(::grpc::ClientContext* context, const ::silicon_based::GetDeviceInfoRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::silicon_based::GetDeviceInfoResponse, ::silicon_based::GetDeviceInfoRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_GetDeviceInfo_, context, request);
}

::grpc::ClientAsyncResponseReader< ::silicon_based::GetDeviceInfoResponse>* CommonCMDService::Stub::AsyncGetDeviceInfoRaw(::grpc::ClientContext* context, const ::silicon_based::GetDeviceInfoRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncGetDeviceInfoRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status CommonCMDService::Stub::SetDebugParam(::grpc::ClientContext* context, const ::silicon_based::DebugParamRequest& request, ::silicon_based::ParamResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::silicon_based::DebugParamRequest, ::silicon_based::ParamResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_SetDebugParam_, context, request, response);
}

void CommonCMDService::Stub::async::SetDebugParam(::grpc::ClientContext* context, const ::silicon_based::DebugParamRequest* request, ::silicon_based::ParamResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::silicon_based::DebugParamRequest, ::silicon_based::ParamResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_SetDebugParam_, context, request, response, std::move(f));
}

void CommonCMDService::Stub::async::SetDebugParam(::grpc::ClientContext* context, const ::silicon_based::DebugParamRequest* request, ::silicon_based::ParamResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_SetDebugParam_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::silicon_based::ParamResponse>* CommonCMDService::Stub::PrepareAsyncSetDebugParamRaw(::grpc::ClientContext* context, const ::silicon_based::DebugParamRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::silicon_based::ParamResponse, ::silicon_based::DebugParamRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_SetDebugParam_, context, request);
}

::grpc::ClientAsyncResponseReader< ::silicon_based::ParamResponse>* CommonCMDService::Stub::AsyncSetDebugParamRaw(::grpc::ClientContext* context, const ::silicon_based::DebugParamRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncSetDebugParamRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status CommonCMDService::Stub::SetGPIOStatus(::grpc::ClientContext* context, const ::silicon_based::GPIOStatusRequest& request, ::silicon_based::ParamResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::silicon_based::GPIOStatusRequest, ::silicon_based::ParamResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_SetGPIOStatus_, context, request, response);
}

void CommonCMDService::Stub::async::SetGPIOStatus(::grpc::ClientContext* context, const ::silicon_based::GPIOStatusRequest* request, ::silicon_based::ParamResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::silicon_based::GPIOStatusRequest, ::silicon_based::ParamResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_SetGPIOStatus_, context, request, response, std::move(f));
}

void CommonCMDService::Stub::async::SetGPIOStatus(::grpc::ClientContext* context, const ::silicon_based::GPIOStatusRequest* request, ::silicon_based::ParamResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_SetGPIOStatus_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::silicon_based::ParamResponse>* CommonCMDService::Stub::PrepareAsyncSetGPIOStatusRaw(::grpc::ClientContext* context, const ::silicon_based::GPIOStatusRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::silicon_based::ParamResponse, ::silicon_based::GPIOStatusRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_SetGPIOStatus_, context, request);
}

::grpc::ClientAsyncResponseReader< ::silicon_based::ParamResponse>* CommonCMDService::Stub::AsyncSetGPIOStatusRaw(::grpc::ClientContext* context, const ::silicon_based::GPIOStatusRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncSetGPIOStatusRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status CommonCMDService::Stub::SetNetCfgAddr(::grpc::ClientContext* context, const ::silicon_based::SetNetCfgRequest& request, ::silicon_based::ParamResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::silicon_based::SetNetCfgRequest, ::silicon_based::ParamResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_SetNetCfgAddr_, context, request, response);
}

void CommonCMDService::Stub::async::SetNetCfgAddr(::grpc::ClientContext* context, const ::silicon_based::SetNetCfgRequest* request, ::silicon_based::ParamResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::silicon_based::SetNetCfgRequest, ::silicon_based::ParamResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_SetNetCfgAddr_, context, request, response, std::move(f));
}

void CommonCMDService::Stub::async::SetNetCfgAddr(::grpc::ClientContext* context, const ::silicon_based::SetNetCfgRequest* request, ::silicon_based::ParamResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_SetNetCfgAddr_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::silicon_based::ParamResponse>* CommonCMDService::Stub::PrepareAsyncSetNetCfgAddrRaw(::grpc::ClientContext* context, const ::silicon_based::SetNetCfgRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::silicon_based::ParamResponse, ::silicon_based::SetNetCfgRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_SetNetCfgAddr_, context, request);
}

::grpc::ClientAsyncResponseReader< ::silicon_based::ParamResponse>* CommonCMDService::Stub::AsyncSetNetCfgAddrRaw(::grpc::ClientContext* context, const ::silicon_based::SetNetCfgRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncSetNetCfgAddrRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status CommonCMDService::Stub::GetNetCfgAddr(::grpc::ClientContext* context, const ::silicon_based::GetNetCfgRequest& request, ::silicon_based::NetCfgResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::silicon_based::GetNetCfgRequest, ::silicon_based::NetCfgResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_GetNetCfgAddr_, context, request, response);
}

void CommonCMDService::Stub::async::GetNetCfgAddr(::grpc::ClientContext* context, const ::silicon_based::GetNetCfgRequest* request, ::silicon_based::NetCfgResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::silicon_based::GetNetCfgRequest, ::silicon_based::NetCfgResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_GetNetCfgAddr_, context, request, response, std::move(f));
}

void CommonCMDService::Stub::async::GetNetCfgAddr(::grpc::ClientContext* context, const ::silicon_based::GetNetCfgRequest* request, ::silicon_based::NetCfgResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_GetNetCfgAddr_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::silicon_based::NetCfgResponse>* CommonCMDService::Stub::PrepareAsyncGetNetCfgAddrRaw(::grpc::ClientContext* context, const ::silicon_based::GetNetCfgRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::silicon_based::NetCfgResponse, ::silicon_based::GetNetCfgRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_GetNetCfgAddr_, context, request);
}

::grpc::ClientAsyncResponseReader< ::silicon_based::NetCfgResponse>* CommonCMDService::Stub::AsyncGetNetCfgAddrRaw(::grpc::ClientContext* context, const ::silicon_based::GetNetCfgRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncGetNetCfgAddrRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status CommonCMDService::Stub::SetRegValue(::grpc::ClientContext* context, const ::silicon_based::RegSetRequest& request, ::silicon_based::ParamResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::silicon_based::RegSetRequest, ::silicon_based::ParamResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_SetRegValue_, context, request, response);
}

void CommonCMDService::Stub::async::SetRegValue(::grpc::ClientContext* context, const ::silicon_based::RegSetRequest* request, ::silicon_based::ParamResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::silicon_based::RegSetRequest, ::silicon_based::ParamResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_SetRegValue_, context, request, response, std::move(f));
}

void CommonCMDService::Stub::async::SetRegValue(::grpc::ClientContext* context, const ::silicon_based::RegSetRequest* request, ::silicon_based::ParamResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_SetRegValue_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::silicon_based::ParamResponse>* CommonCMDService::Stub::PrepareAsyncSetRegValueRaw(::grpc::ClientContext* context, const ::silicon_based::RegSetRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::silicon_based::ParamResponse, ::silicon_based::RegSetRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_SetRegValue_, context, request);
}

::grpc::ClientAsyncResponseReader< ::silicon_based::ParamResponse>* CommonCMDService::Stub::AsyncSetRegValueRaw(::grpc::ClientContext* context, const ::silicon_based::RegSetRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncSetRegValueRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status CommonCMDService::Stub::GetRegValue(::grpc::ClientContext* context, const ::silicon_based::RegGetRequest& request, ::silicon_based::RegValueResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::silicon_based::RegGetRequest, ::silicon_based::RegValueResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_GetRegValue_, context, request, response);
}

void CommonCMDService::Stub::async::GetRegValue(::grpc::ClientContext* context, const ::silicon_based::RegGetRequest* request, ::silicon_based::RegValueResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::silicon_based::RegGetRequest, ::silicon_based::RegValueResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_GetRegValue_, context, request, response, std::move(f));
}

void CommonCMDService::Stub::async::GetRegValue(::grpc::ClientContext* context, const ::silicon_based::RegGetRequest* request, ::silicon_based::RegValueResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_GetRegValue_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::silicon_based::RegValueResponse>* CommonCMDService::Stub::PrepareAsyncGetRegValueRaw(::grpc::ClientContext* context, const ::silicon_based::RegGetRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::silicon_based::RegValueResponse, ::silicon_based::RegGetRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_GetRegValue_, context, request);
}

::grpc::ClientAsyncResponseReader< ::silicon_based::RegValueResponse>* CommonCMDService::Stub::AsyncGetRegValueRaw(::grpc::ClientContext* context, const ::silicon_based::RegGetRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncGetRegValueRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status CommonCMDService::Stub::SetPCIERegValue(::grpc::ClientContext* context, const ::silicon_based::PCIERegSetRequest& request, ::silicon_based::ParamResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::silicon_based::PCIERegSetRequest, ::silicon_based::ParamResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_SetPCIERegValue_, context, request, response);
}

void CommonCMDService::Stub::async::SetPCIERegValue(::grpc::ClientContext* context, const ::silicon_based::PCIERegSetRequest* request, ::silicon_based::ParamResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::silicon_based::PCIERegSetRequest, ::silicon_based::ParamResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_SetPCIERegValue_, context, request, response, std::move(f));
}

void CommonCMDService::Stub::async::SetPCIERegValue(::grpc::ClientContext* context, const ::silicon_based::PCIERegSetRequest* request, ::silicon_based::ParamResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_SetPCIERegValue_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::silicon_based::ParamResponse>* CommonCMDService::Stub::PrepareAsyncSetPCIERegValueRaw(::grpc::ClientContext* context, const ::silicon_based::PCIERegSetRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::silicon_based::ParamResponse, ::silicon_based::PCIERegSetRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_SetPCIERegValue_, context, request);
}

::grpc::ClientAsyncResponseReader< ::silicon_based::ParamResponse>* CommonCMDService::Stub::AsyncSetPCIERegValueRaw(::grpc::ClientContext* context, const ::silicon_based::PCIERegSetRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncSetPCIERegValueRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status CommonCMDService::Stub::GetPCIERegValue(::grpc::ClientContext* context, const ::silicon_based::PCIERegGetRequest& request, ::silicon_based::PCIERegValueResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::silicon_based::PCIERegGetRequest, ::silicon_based::PCIERegValueResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_GetPCIERegValue_, context, request, response);
}

void CommonCMDService::Stub::async::GetPCIERegValue(::grpc::ClientContext* context, const ::silicon_based::PCIERegGetRequest* request, ::silicon_based::PCIERegValueResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::silicon_based::PCIERegGetRequest, ::silicon_based::PCIERegValueResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_GetPCIERegValue_, context, request, response, std::move(f));
}

void CommonCMDService::Stub::async::GetPCIERegValue(::grpc::ClientContext* context, const ::silicon_based::PCIERegGetRequest* request, ::silicon_based::PCIERegValueResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_GetPCIERegValue_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::silicon_based::PCIERegValueResponse>* CommonCMDService::Stub::PrepareAsyncGetPCIERegValueRaw(::grpc::ClientContext* context, const ::silicon_based::PCIERegGetRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::silicon_based::PCIERegValueResponse, ::silicon_based::PCIERegGetRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_GetPCIERegValue_, context, request);
}

::grpc::ClientAsyncResponseReader< ::silicon_based::PCIERegValueResponse>* CommonCMDService::Stub::AsyncGetPCIERegValueRaw(::grpc::ClientContext* context, const ::silicon_based::PCIERegGetRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncGetPCIERegValueRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::ClientWriter< ::silicon_based::SetStreamDataRequest>* CommonCMDService::Stub::StreamDataSetRaw(::grpc::ClientContext* context, ::silicon_based::SetStreamResult* response) {
  return ::grpc::internal::ClientWriterFactory< ::silicon_based::SetStreamDataRequest>::Create(channel_.get(), rpcmethod_StreamDataSet_, context, response);
}

void CommonCMDService::Stub::async::StreamDataSet(::grpc::ClientContext* context, ::silicon_based::SetStreamResult* response, ::grpc::ClientWriteReactor< ::silicon_based::SetStreamDataRequest>* reactor) {
  ::grpc::internal::ClientCallbackWriterFactory< ::silicon_based::SetStreamDataRequest>::Create(stub_->channel_.get(), stub_->rpcmethod_StreamDataSet_, context, response, reactor);
}

::grpc::ClientAsyncWriter< ::silicon_based::SetStreamDataRequest>* CommonCMDService::Stub::AsyncStreamDataSetRaw(::grpc::ClientContext* context, ::silicon_based::SetStreamResult* response, ::grpc::CompletionQueue* cq, void* tag) {
  return ::grpc::internal::ClientAsyncWriterFactory< ::silicon_based::SetStreamDataRequest>::Create(channel_.get(), cq, rpcmethod_StreamDataSet_, context, response, true, tag);
}

::grpc::ClientAsyncWriter< ::silicon_based::SetStreamDataRequest>* CommonCMDService::Stub::PrepareAsyncStreamDataSetRaw(::grpc::ClientContext* context, ::silicon_based::SetStreamResult* response, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncWriterFactory< ::silicon_based::SetStreamDataRequest>::Create(channel_.get(), cq, rpcmethod_StreamDataSet_, context, response, false, nullptr);
}

::grpc::ClientReader< ::silicon_based::GetStreamResult>* CommonCMDService::Stub::StreamDataGetRaw(::grpc::ClientContext* context, const ::silicon_based::GetStreamDataRequest& request) {
  return ::grpc::internal::ClientReaderFactory< ::silicon_based::GetStreamResult>::Create(channel_.get(), rpcmethod_StreamDataGet_, context, request);
}

void CommonCMDService::Stub::async::StreamDataGet(::grpc::ClientContext* context, const ::silicon_based::GetStreamDataRequest* request, ::grpc::ClientReadReactor< ::silicon_based::GetStreamResult>* reactor) {
  ::grpc::internal::ClientCallbackReaderFactory< ::silicon_based::GetStreamResult>::Create(stub_->channel_.get(), stub_->rpcmethod_StreamDataGet_, context, request, reactor);
}

::grpc::ClientAsyncReader< ::silicon_based::GetStreamResult>* CommonCMDService::Stub::AsyncStreamDataGetRaw(::grpc::ClientContext* context, const ::silicon_based::GetStreamDataRequest& request, ::grpc::CompletionQueue* cq, void* tag) {
  return ::grpc::internal::ClientAsyncReaderFactory< ::silicon_based::GetStreamResult>::Create(channel_.get(), cq, rpcmethod_StreamDataGet_, context, request, true, tag);
}

::grpc::ClientAsyncReader< ::silicon_based::GetStreamResult>* CommonCMDService::Stub::PrepareAsyncStreamDataGetRaw(::grpc::ClientContext* context, const ::silicon_based::GetStreamDataRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncReaderFactory< ::silicon_based::GetStreamResult>::Create(channel_.get(), cq, rpcmethod_StreamDataGet_, context, request, false, nullptr);
}

::grpc::Status CommonCMDService::Stub::SetDevTrigSource(::grpc::ClientContext* context, const ::silicon_based::SetTrigSourceRequest& request, ::silicon_based::ParamResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::silicon_based::SetTrigSourceRequest, ::silicon_based::ParamResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_SetDevTrigSource_, context, request, response);
}

void CommonCMDService::Stub::async::SetDevTrigSource(::grpc::ClientContext* context, const ::silicon_based::SetTrigSourceRequest* request, ::silicon_based::ParamResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::silicon_based::SetTrigSourceRequest, ::silicon_based::ParamResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_SetDevTrigSource_, context, request, response, std::move(f));
}

void CommonCMDService::Stub::async::SetDevTrigSource(::grpc::ClientContext* context, const ::silicon_based::SetTrigSourceRequest* request, ::silicon_based::ParamResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_SetDevTrigSource_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::silicon_based::ParamResponse>* CommonCMDService::Stub::PrepareAsyncSetDevTrigSourceRaw(::grpc::ClientContext* context, const ::silicon_based::SetTrigSourceRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::silicon_based::ParamResponse, ::silicon_based::SetTrigSourceRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_SetDevTrigSource_, context, request);
}

::grpc::ClientAsyncResponseReader< ::silicon_based::ParamResponse>* CommonCMDService::Stub::AsyncSetDevTrigSourceRaw(::grpc::ClientContext* context, const ::silicon_based::SetTrigSourceRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncSetDevTrigSourceRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status CommonCMDService::Stub::GetDevTrigSource(::grpc::ClientContext* context, const ::silicon_based::GetTrigSourceRequest& request, ::silicon_based::GetTrigSourceResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::silicon_based::GetTrigSourceRequest, ::silicon_based::GetTrigSourceResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_GetDevTrigSource_, context, request, response);
}

void CommonCMDService::Stub::async::GetDevTrigSource(::grpc::ClientContext* context, const ::silicon_based::GetTrigSourceRequest* request, ::silicon_based::GetTrigSourceResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::silicon_based::GetTrigSourceRequest, ::silicon_based::GetTrigSourceResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_GetDevTrigSource_, context, request, response, std::move(f));
}

void CommonCMDService::Stub::async::GetDevTrigSource(::grpc::ClientContext* context, const ::silicon_based::GetTrigSourceRequest* request, ::silicon_based::GetTrigSourceResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_GetDevTrigSource_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::silicon_based::GetTrigSourceResponse>* CommonCMDService::Stub::PrepareAsyncGetDevTrigSourceRaw(::grpc::ClientContext* context, const ::silicon_based::GetTrigSourceRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::silicon_based::GetTrigSourceResponse, ::silicon_based::GetTrigSourceRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_GetDevTrigSource_, context, request);
}

::grpc::ClientAsyncResponseReader< ::silicon_based::GetTrigSourceResponse>* CommonCMDService::Stub::AsyncGetDevTrigSourceRaw(::grpc::ClientContext* context, const ::silicon_based::GetTrigSourceRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncGetDevTrigSourceRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status CommonCMDService::Stub::SetDevTrigParam(::grpc::ClientContext* context, const ::silicon_based::SetTrigParamRequest& request, ::silicon_based::ParamResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::silicon_based::SetTrigParamRequest, ::silicon_based::ParamResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_SetDevTrigParam_, context, request, response);
}

void CommonCMDService::Stub::async::SetDevTrigParam(::grpc::ClientContext* context, const ::silicon_based::SetTrigParamRequest* request, ::silicon_based::ParamResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::silicon_based::SetTrigParamRequest, ::silicon_based::ParamResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_SetDevTrigParam_, context, request, response, std::move(f));
}

void CommonCMDService::Stub::async::SetDevTrigParam(::grpc::ClientContext* context, const ::silicon_based::SetTrigParamRequest* request, ::silicon_based::ParamResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_SetDevTrigParam_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::silicon_based::ParamResponse>* CommonCMDService::Stub::PrepareAsyncSetDevTrigParamRaw(::grpc::ClientContext* context, const ::silicon_based::SetTrigParamRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::silicon_based::ParamResponse, ::silicon_based::SetTrigParamRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_SetDevTrigParam_, context, request);
}

::grpc::ClientAsyncResponseReader< ::silicon_based::ParamResponse>* CommonCMDService::Stub::AsyncSetDevTrigParamRaw(::grpc::ClientContext* context, const ::silicon_based::SetTrigParamRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncSetDevTrigParamRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status CommonCMDService::Stub::GetDevTrigParam(::grpc::ClientContext* context, const ::silicon_based::GetTrigParamRequest& request, ::silicon_based::GetTrigParamResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::silicon_based::GetTrigParamRequest, ::silicon_based::GetTrigParamResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_GetDevTrigParam_, context, request, response);
}

void CommonCMDService::Stub::async::GetDevTrigParam(::grpc::ClientContext* context, const ::silicon_based::GetTrigParamRequest* request, ::silicon_based::GetTrigParamResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::silicon_based::GetTrigParamRequest, ::silicon_based::GetTrigParamResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_GetDevTrigParam_, context, request, response, std::move(f));
}

void CommonCMDService::Stub::async::GetDevTrigParam(::grpc::ClientContext* context, const ::silicon_based::GetTrigParamRequest* request, ::silicon_based::GetTrigParamResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_GetDevTrigParam_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::silicon_based::GetTrigParamResponse>* CommonCMDService::Stub::PrepareAsyncGetDevTrigParamRaw(::grpc::ClientContext* context, const ::silicon_based::GetTrigParamRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::silicon_based::GetTrigParamResponse, ::silicon_based::GetTrigParamRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_GetDevTrigParam_, context, request);
}

::grpc::ClientAsyncResponseReader< ::silicon_based::GetTrigParamResponse>* CommonCMDService::Stub::AsyncGetDevTrigParamRaw(::grpc::ClientContext* context, const ::silicon_based::GetTrigParamRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncGetDevTrigParamRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status CommonCMDService::Stub::SetTrigStart(::grpc::ClientContext* context, const ::silicon_based::SetTrigStartRequest& request, ::silicon_based::ParamResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::silicon_based::SetTrigStartRequest, ::silicon_based::ParamResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_SetTrigStart_, context, request, response);
}

void CommonCMDService::Stub::async::SetTrigStart(::grpc::ClientContext* context, const ::silicon_based::SetTrigStartRequest* request, ::silicon_based::ParamResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::silicon_based::SetTrigStartRequest, ::silicon_based::ParamResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_SetTrigStart_, context, request, response, std::move(f));
}

void CommonCMDService::Stub::async::SetTrigStart(::grpc::ClientContext* context, const ::silicon_based::SetTrigStartRequest* request, ::silicon_based::ParamResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_SetTrigStart_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::silicon_based::ParamResponse>* CommonCMDService::Stub::PrepareAsyncSetTrigStartRaw(::grpc::ClientContext* context, const ::silicon_based::SetTrigStartRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::silicon_based::ParamResponse, ::silicon_based::SetTrigStartRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_SetTrigStart_, context, request);
}

::grpc::ClientAsyncResponseReader< ::silicon_based::ParamResponse>* CommonCMDService::Stub::AsyncSetTrigStartRaw(::grpc::ClientContext* context, const ::silicon_based::SetTrigStartRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncSetTrigStartRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status CommonCMDService::Stub::SetRERIOFeadbackTest(::grpc::ClientContext* context, const ::silicon_based::SetRERIOFeadbackTestRequest& request, ::silicon_based::ParamResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::silicon_based::SetRERIOFeadbackTestRequest, ::silicon_based::ParamResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_SetRERIOFeadbackTest_, context, request, response);
}

void CommonCMDService::Stub::async::SetRERIOFeadbackTest(::grpc::ClientContext* context, const ::silicon_based::SetRERIOFeadbackTestRequest* request, ::silicon_based::ParamResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::silicon_based::SetRERIOFeadbackTestRequest, ::silicon_based::ParamResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_SetRERIOFeadbackTest_, context, request, response, std::move(f));
}

void CommonCMDService::Stub::async::SetRERIOFeadbackTest(::grpc::ClientContext* context, const ::silicon_based::SetRERIOFeadbackTestRequest* request, ::silicon_based::ParamResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_SetRERIOFeadbackTest_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::silicon_based::ParamResponse>* CommonCMDService::Stub::PrepareAsyncSetRERIOFeadbackTestRaw(::grpc::ClientContext* context, const ::silicon_based::SetRERIOFeadbackTestRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::silicon_based::ParamResponse, ::silicon_based::SetRERIOFeadbackTestRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_SetRERIOFeadbackTest_, context, request);
}

::grpc::ClientAsyncResponseReader< ::silicon_based::ParamResponse>* CommonCMDService::Stub::AsyncSetRERIOFeadbackTestRaw(::grpc::ClientContext* context, const ::silicon_based::SetRERIOFeadbackTestRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncSetRERIOFeadbackTestRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status CommonCMDService::Stub::GetRERIOFeadbackTest(::grpc::ClientContext* context, const ::silicon_based::GetRERIOFeadbackTestRequest& request, ::silicon_based::GetRERIOFeadbackTestResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::silicon_based::GetRERIOFeadbackTestRequest, ::silicon_based::GetRERIOFeadbackTestResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_GetRERIOFeadbackTest_, context, request, response);
}

void CommonCMDService::Stub::async::GetRERIOFeadbackTest(::grpc::ClientContext* context, const ::silicon_based::GetRERIOFeadbackTestRequest* request, ::silicon_based::GetRERIOFeadbackTestResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::silicon_based::GetRERIOFeadbackTestRequest, ::silicon_based::GetRERIOFeadbackTestResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_GetRERIOFeadbackTest_, context, request, response, std::move(f));
}

void CommonCMDService::Stub::async::GetRERIOFeadbackTest(::grpc::ClientContext* context, const ::silicon_based::GetRERIOFeadbackTestRequest* request, ::silicon_based::GetRERIOFeadbackTestResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_GetRERIOFeadbackTest_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::silicon_based::GetRERIOFeadbackTestResponse>* CommonCMDService::Stub::PrepareAsyncGetRERIOFeadbackTestRaw(::grpc::ClientContext* context, const ::silicon_based::GetRERIOFeadbackTestRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::silicon_based::GetRERIOFeadbackTestResponse, ::silicon_based::GetRERIOFeadbackTestRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_GetRERIOFeadbackTest_, context, request);
}

::grpc::ClientAsyncResponseReader< ::silicon_based::GetRERIOFeadbackTestResponse>* CommonCMDService::Stub::AsyncGetRERIOFeadbackTestRaw(::grpc::ClientContext* context, const ::silicon_based::GetRERIOFeadbackTestRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncGetRERIOFeadbackTestRaw(context, request, cq);
  result->StartCall();
  return result;
}

CommonCMDService::Service::Service() {
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      CommonCMDService_method_names[0],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< CommonCMDService::Service, ::silicon_based::GetIDNRequest, ::silicon_based::GetIDNResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](CommonCMDService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::silicon_based::GetIDNRequest* req,
             ::silicon_based::GetIDNResponse* resp) {
               return service->GetIDN(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      CommonCMDService_method_names[1],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< CommonCMDService::Service, ::silicon_based::GetDeviceInfoRequest, ::silicon_based::GetDeviceInfoResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](CommonCMDService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::silicon_based::GetDeviceInfoRequest* req,
             ::silicon_based::GetDeviceInfoResponse* resp) {
               return service->GetDeviceInfo(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      CommonCMDService_method_names[2],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< CommonCMDService::Service, ::silicon_based::DebugParamRequest, ::silicon_based::ParamResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](CommonCMDService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::silicon_based::DebugParamRequest* req,
             ::silicon_based::ParamResponse* resp) {
               return service->SetDebugParam(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      CommonCMDService_method_names[3],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< CommonCMDService::Service, ::silicon_based::GPIOStatusRequest, ::silicon_based::ParamResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](CommonCMDService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::silicon_based::GPIOStatusRequest* req,
             ::silicon_based::ParamResponse* resp) {
               return service->SetGPIOStatus(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      CommonCMDService_method_names[4],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< CommonCMDService::Service, ::silicon_based::SetNetCfgRequest, ::silicon_based::ParamResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](CommonCMDService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::silicon_based::SetNetCfgRequest* req,
             ::silicon_based::ParamResponse* resp) {
               return service->SetNetCfgAddr(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      CommonCMDService_method_names[5],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< CommonCMDService::Service, ::silicon_based::GetNetCfgRequest, ::silicon_based::NetCfgResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](CommonCMDService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::silicon_based::GetNetCfgRequest* req,
             ::silicon_based::NetCfgResponse* resp) {
               return service->GetNetCfgAddr(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      CommonCMDService_method_names[6],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< CommonCMDService::Service, ::silicon_based::RegSetRequest, ::silicon_based::ParamResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](CommonCMDService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::silicon_based::RegSetRequest* req,
             ::silicon_based::ParamResponse* resp) {
               return service->SetRegValue(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      CommonCMDService_method_names[7],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< CommonCMDService::Service, ::silicon_based::RegGetRequest, ::silicon_based::RegValueResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](CommonCMDService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::silicon_based::RegGetRequest* req,
             ::silicon_based::RegValueResponse* resp) {
               return service->GetRegValue(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      CommonCMDService_method_names[8],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< CommonCMDService::Service, ::silicon_based::PCIERegSetRequest, ::silicon_based::ParamResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](CommonCMDService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::silicon_based::PCIERegSetRequest* req,
             ::silicon_based::ParamResponse* resp) {
               return service->SetPCIERegValue(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      CommonCMDService_method_names[9],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< CommonCMDService::Service, ::silicon_based::PCIERegGetRequest, ::silicon_based::PCIERegValueResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](CommonCMDService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::silicon_based::PCIERegGetRequest* req,
             ::silicon_based::PCIERegValueResponse* resp) {
               return service->GetPCIERegValue(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      CommonCMDService_method_names[10],
      ::grpc::internal::RpcMethod::CLIENT_STREAMING,
      new ::grpc::internal::ClientStreamingHandler< CommonCMDService::Service, ::silicon_based::SetStreamDataRequest, ::silicon_based::SetStreamResult>(
          [](CommonCMDService::Service* service,
             ::grpc::ServerContext* ctx,
             ::grpc::ServerReader<::silicon_based::SetStreamDataRequest>* reader,
             ::silicon_based::SetStreamResult* resp) {
               return service->StreamDataSet(ctx, reader, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      CommonCMDService_method_names[11],
      ::grpc::internal::RpcMethod::SERVER_STREAMING,
      new ::grpc::internal::ServerStreamingHandler< CommonCMDService::Service, ::silicon_based::GetStreamDataRequest, ::silicon_based::GetStreamResult>(
          [](CommonCMDService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::silicon_based::GetStreamDataRequest* req,
             ::grpc::ServerWriter<::silicon_based::GetStreamResult>* writer) {
               return service->StreamDataGet(ctx, req, writer);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      CommonCMDService_method_names[12],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< CommonCMDService::Service, ::silicon_based::SetTrigSourceRequest, ::silicon_based::ParamResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](CommonCMDService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::silicon_based::SetTrigSourceRequest* req,
             ::silicon_based::ParamResponse* resp) {
               return service->SetDevTrigSource(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      CommonCMDService_method_names[13],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< CommonCMDService::Service, ::silicon_based::GetTrigSourceRequest, ::silicon_based::GetTrigSourceResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](CommonCMDService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::silicon_based::GetTrigSourceRequest* req,
             ::silicon_based::GetTrigSourceResponse* resp) {
               return service->GetDevTrigSource(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      CommonCMDService_method_names[14],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< CommonCMDService::Service, ::silicon_based::SetTrigParamRequest, ::silicon_based::ParamResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](CommonCMDService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::silicon_based::SetTrigParamRequest* req,
             ::silicon_based::ParamResponse* resp) {
               return service->SetDevTrigParam(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      CommonCMDService_method_names[15],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< CommonCMDService::Service, ::silicon_based::GetTrigParamRequest, ::silicon_based::GetTrigParamResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](CommonCMDService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::silicon_based::GetTrigParamRequest* req,
             ::silicon_based::GetTrigParamResponse* resp) {
               return service->GetDevTrigParam(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      CommonCMDService_method_names[16],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< CommonCMDService::Service, ::silicon_based::SetTrigStartRequest, ::silicon_based::ParamResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](CommonCMDService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::silicon_based::SetTrigStartRequest* req,
             ::silicon_based::ParamResponse* resp) {
               return service->SetTrigStart(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      CommonCMDService_method_names[17],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< CommonCMDService::Service, ::silicon_based::SetRERIOFeadbackTestRequest, ::silicon_based::ParamResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](CommonCMDService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::silicon_based::SetRERIOFeadbackTestRequest* req,
             ::silicon_based::ParamResponse* resp) {
               return service->SetRERIOFeadbackTest(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      CommonCMDService_method_names[18],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< CommonCMDService::Service, ::silicon_based::GetRERIOFeadbackTestRequest, ::silicon_based::GetRERIOFeadbackTestResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](CommonCMDService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::silicon_based::GetRERIOFeadbackTestRequest* req,
             ::silicon_based::GetRERIOFeadbackTestResponse* resp) {
               return service->GetRERIOFeadbackTest(ctx, req, resp);
             }, this)));
}

CommonCMDService::Service::~Service() {
}

::grpc::Status CommonCMDService::Service::GetIDN(::grpc::ServerContext* context, const ::silicon_based::GetIDNRequest* request, ::silicon_based::GetIDNResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status CommonCMDService::Service::GetDeviceInfo(::grpc::ServerContext* context, const ::silicon_based::GetDeviceInfoRequest* request, ::silicon_based::GetDeviceInfoResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status CommonCMDService::Service::SetDebugParam(::grpc::ServerContext* context, const ::silicon_based::DebugParamRequest* request, ::silicon_based::ParamResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status CommonCMDService::Service::SetGPIOStatus(::grpc::ServerContext* context, const ::silicon_based::GPIOStatusRequest* request, ::silicon_based::ParamResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status CommonCMDService::Service::SetNetCfgAddr(::grpc::ServerContext* context, const ::silicon_based::SetNetCfgRequest* request, ::silicon_based::ParamResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status CommonCMDService::Service::GetNetCfgAddr(::grpc::ServerContext* context, const ::silicon_based::GetNetCfgRequest* request, ::silicon_based::NetCfgResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status CommonCMDService::Service::SetRegValue(::grpc::ServerContext* context, const ::silicon_based::RegSetRequest* request, ::silicon_based::ParamResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status CommonCMDService::Service::GetRegValue(::grpc::ServerContext* context, const ::silicon_based::RegGetRequest* request, ::silicon_based::RegValueResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status CommonCMDService::Service::SetPCIERegValue(::grpc::ServerContext* context, const ::silicon_based::PCIERegSetRequest* request, ::silicon_based::ParamResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status CommonCMDService::Service::GetPCIERegValue(::grpc::ServerContext* context, const ::silicon_based::PCIERegGetRequest* request, ::silicon_based::PCIERegValueResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status CommonCMDService::Service::StreamDataSet(::grpc::ServerContext* context, ::grpc::ServerReader< ::silicon_based::SetStreamDataRequest>* reader, ::silicon_based::SetStreamResult* response) {
  (void) context;
  (void) reader;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status CommonCMDService::Service::StreamDataGet(::grpc::ServerContext* context, const ::silicon_based::GetStreamDataRequest* request, ::grpc::ServerWriter< ::silicon_based::GetStreamResult>* writer) {
  (void) context;
  (void) request;
  (void) writer;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status CommonCMDService::Service::SetDevTrigSource(::grpc::ServerContext* context, const ::silicon_based::SetTrigSourceRequest* request, ::silicon_based::ParamResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status CommonCMDService::Service::GetDevTrigSource(::grpc::ServerContext* context, const ::silicon_based::GetTrigSourceRequest* request, ::silicon_based::GetTrigSourceResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status CommonCMDService::Service::SetDevTrigParam(::grpc::ServerContext* context, const ::silicon_based::SetTrigParamRequest* request, ::silicon_based::ParamResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status CommonCMDService::Service::GetDevTrigParam(::grpc::ServerContext* context, const ::silicon_based::GetTrigParamRequest* request, ::silicon_based::GetTrigParamResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status CommonCMDService::Service::SetTrigStart(::grpc::ServerContext* context, const ::silicon_based::SetTrigStartRequest* request, ::silicon_based::ParamResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status CommonCMDService::Service::SetRERIOFeadbackTest(::grpc::ServerContext* context, const ::silicon_based::SetRERIOFeadbackTestRequest* request, ::silicon_based::ParamResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status CommonCMDService::Service::GetRERIOFeadbackTest(::grpc::ServerContext* context, const ::silicon_based::GetRERIOFeadbackTestRequest* request, ::silicon_based::GetRERIOFeadbackTestResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}


}  // namespace silicon_based

