// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: lnawg_cmd.proto

#include "lnawg_cmd.pb.h"
#include "lnawg_cmd.grpc.pb.h"

#include <functional>
#include <grpcpp/support/async_stream.h>
#include <grpcpp/support/async_unary_call.h>
#include <grpcpp/impl/channel_interface.h>
#include <grpcpp/impl/client_unary_call.h>
#include <grpcpp/support/client_callback.h>
#include <grpcpp/support/message_allocator.h>
#include <grpcpp/support/method_handler.h>
#include <grpcpp/impl/rpc_service_method.h>
#include <grpcpp/support/server_callback.h>
#include <grpcpp/impl/server_callback_handlers.h>
#include <grpcpp/server_context.h>
#include <grpcpp/impl/service_type.h>
#include <grpcpp/support/sync_stream.h>
namespace silicon_based {

static const char* LNAWGCMDService_method_names[] = {
  "/silicon_based.LNAWGCMDService/SetMode",
  "/silicon_based.LNAWGCMDService/GetMode",
  "/silicon_based.LNAWGCMDService/SetRun",
  "/silicon_based.LNAWGCMDService/GetRun",
  "/silicon_based.LNAWGCMDService/SetExtSource",
  "/silicon_based.LNAWGCMDService/GetExtSource",
  "/silicon_based.LNAWGCMDService/SetRange",
  "/silicon_based.LNAWGCMDService/GetRange",
  "/silicon_based.LNAWGCMDService/SetOffset",
  "/silicon_based.LNAWGCMDService/GetOffset",
  "/silicon_based.LNAWGCMDService/SetSegmentCount",
  "/silicon_based.LNAWGCMDService/GetSegmentCount",
  "/silicon_based.LNAWGCMDService/SetLoopCount",
  "/silicon_based.LNAWGCMDService/GetLoopCount",
  "/silicon_based.LNAWGCMDService/SetDDSParam",
  "/silicon_based.LNAWGCMDService/GetDDSParam",
  "/silicon_based.LNAWGCMDService/SetChirpOutParam",
  "/silicon_based.LNAWGCMDService/GetChirpOutParam",
  "/silicon_based.LNAWGCMDService/SetDDSEnable",
  "/silicon_based.LNAWGCMDService/GetDDSEnable",
};

std::unique_ptr< LNAWGCMDService::Stub> LNAWGCMDService::NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options) {
  (void)options;
  std::unique_ptr< LNAWGCMDService::Stub> stub(new LNAWGCMDService::Stub(channel, options));
  return stub;
}

LNAWGCMDService::Stub::Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options)
  : channel_(channel), rpcmethod_SetMode_(LNAWGCMDService_method_names[0], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_GetMode_(LNAWGCMDService_method_names[1], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_SetRun_(LNAWGCMDService_method_names[2], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_GetRun_(LNAWGCMDService_method_names[3], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_SetExtSource_(LNAWGCMDService_method_names[4], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_GetExtSource_(LNAWGCMDService_method_names[5], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_SetRange_(LNAWGCMDService_method_names[6], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_GetRange_(LNAWGCMDService_method_names[7], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_SetOffset_(LNAWGCMDService_method_names[8], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_GetOffset_(LNAWGCMDService_method_names[9], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_SetSegmentCount_(LNAWGCMDService_method_names[10], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_GetSegmentCount_(LNAWGCMDService_method_names[11], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_SetLoopCount_(LNAWGCMDService_method_names[12], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_GetLoopCount_(LNAWGCMDService_method_names[13], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_SetDDSParam_(LNAWGCMDService_method_names[14], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_GetDDSParam_(LNAWGCMDService_method_names[15], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_SetChirpOutParam_(LNAWGCMDService_method_names[16], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_GetChirpOutParam_(LNAWGCMDService_method_names[17], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_SetDDSEnable_(LNAWGCMDService_method_names[18], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_GetDDSEnable_(LNAWGCMDService_method_names[19], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  {}

::grpc::Status LNAWGCMDService::Stub::SetMode(::grpc::ClientContext* context, const ::silicon_based::ModeSetRequest& request, ::silicon_based::ParamResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::silicon_based::ModeSetRequest, ::silicon_based::ParamResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_SetMode_, context, request, response);
}

void LNAWGCMDService::Stub::async::SetMode(::grpc::ClientContext* context, const ::silicon_based::ModeSetRequest* request, ::silicon_based::ParamResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::silicon_based::ModeSetRequest, ::silicon_based::ParamResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_SetMode_, context, request, response, std::move(f));
}

void LNAWGCMDService::Stub::async::SetMode(::grpc::ClientContext* context, const ::silicon_based::ModeSetRequest* request, ::silicon_based::ParamResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_SetMode_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::silicon_based::ParamResponse>* LNAWGCMDService::Stub::PrepareAsyncSetModeRaw(::grpc::ClientContext* context, const ::silicon_based::ModeSetRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::silicon_based::ParamResponse, ::silicon_based::ModeSetRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_SetMode_, context, request);
}

::grpc::ClientAsyncResponseReader< ::silicon_based::ParamResponse>* LNAWGCMDService::Stub::AsyncSetModeRaw(::grpc::ClientContext* context, const ::silicon_based::ModeSetRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncSetModeRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status LNAWGCMDService::Stub::GetMode(::grpc::ClientContext* context, const ::silicon_based::ModeGetRequest& request, ::silicon_based::ModeGetResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::silicon_based::ModeGetRequest, ::silicon_based::ModeGetResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_GetMode_, context, request, response);
}

void LNAWGCMDService::Stub::async::GetMode(::grpc::ClientContext* context, const ::silicon_based::ModeGetRequest* request, ::silicon_based::ModeGetResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::silicon_based::ModeGetRequest, ::silicon_based::ModeGetResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_GetMode_, context, request, response, std::move(f));
}

void LNAWGCMDService::Stub::async::GetMode(::grpc::ClientContext* context, const ::silicon_based::ModeGetRequest* request, ::silicon_based::ModeGetResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_GetMode_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::silicon_based::ModeGetResponse>* LNAWGCMDService::Stub::PrepareAsyncGetModeRaw(::grpc::ClientContext* context, const ::silicon_based::ModeGetRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::silicon_based::ModeGetResponse, ::silicon_based::ModeGetRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_GetMode_, context, request);
}

::grpc::ClientAsyncResponseReader< ::silicon_based::ModeGetResponse>* LNAWGCMDService::Stub::AsyncGetModeRaw(::grpc::ClientContext* context, const ::silicon_based::ModeGetRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncGetModeRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status LNAWGCMDService::Stub::SetRun(::grpc::ClientContext* context, const ::silicon_based::RunSetRequest& request, ::silicon_based::ParamResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::silicon_based::RunSetRequest, ::silicon_based::ParamResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_SetRun_, context, request, response);
}

void LNAWGCMDService::Stub::async::SetRun(::grpc::ClientContext* context, const ::silicon_based::RunSetRequest* request, ::silicon_based::ParamResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::silicon_based::RunSetRequest, ::silicon_based::ParamResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_SetRun_, context, request, response, std::move(f));
}

void LNAWGCMDService::Stub::async::SetRun(::grpc::ClientContext* context, const ::silicon_based::RunSetRequest* request, ::silicon_based::ParamResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_SetRun_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::silicon_based::ParamResponse>* LNAWGCMDService::Stub::PrepareAsyncSetRunRaw(::grpc::ClientContext* context, const ::silicon_based::RunSetRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::silicon_based::ParamResponse, ::silicon_based::RunSetRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_SetRun_, context, request);
}

::grpc::ClientAsyncResponseReader< ::silicon_based::ParamResponse>* LNAWGCMDService::Stub::AsyncSetRunRaw(::grpc::ClientContext* context, const ::silicon_based::RunSetRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncSetRunRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status LNAWGCMDService::Stub::GetRun(::grpc::ClientContext* context, const ::silicon_based::RunGetRequest& request, ::silicon_based::RunGetResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::silicon_based::RunGetRequest, ::silicon_based::RunGetResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_GetRun_, context, request, response);
}

void LNAWGCMDService::Stub::async::GetRun(::grpc::ClientContext* context, const ::silicon_based::RunGetRequest* request, ::silicon_based::RunGetResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::silicon_based::RunGetRequest, ::silicon_based::RunGetResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_GetRun_, context, request, response, std::move(f));
}

void LNAWGCMDService::Stub::async::GetRun(::grpc::ClientContext* context, const ::silicon_based::RunGetRequest* request, ::silicon_based::RunGetResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_GetRun_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::silicon_based::RunGetResponse>* LNAWGCMDService::Stub::PrepareAsyncGetRunRaw(::grpc::ClientContext* context, const ::silicon_based::RunGetRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::silicon_based::RunGetResponse, ::silicon_based::RunGetRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_GetRun_, context, request);
}

::grpc::ClientAsyncResponseReader< ::silicon_based::RunGetResponse>* LNAWGCMDService::Stub::AsyncGetRunRaw(::grpc::ClientContext* context, const ::silicon_based::RunGetRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncGetRunRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status LNAWGCMDService::Stub::SetExtSource(::grpc::ClientContext* context, const ::silicon_based::ExtSourceSetRequest& request, ::silicon_based::ParamResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::silicon_based::ExtSourceSetRequest, ::silicon_based::ParamResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_SetExtSource_, context, request, response);
}

void LNAWGCMDService::Stub::async::SetExtSource(::grpc::ClientContext* context, const ::silicon_based::ExtSourceSetRequest* request, ::silicon_based::ParamResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::silicon_based::ExtSourceSetRequest, ::silicon_based::ParamResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_SetExtSource_, context, request, response, std::move(f));
}

void LNAWGCMDService::Stub::async::SetExtSource(::grpc::ClientContext* context, const ::silicon_based::ExtSourceSetRequest* request, ::silicon_based::ParamResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_SetExtSource_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::silicon_based::ParamResponse>* LNAWGCMDService::Stub::PrepareAsyncSetExtSourceRaw(::grpc::ClientContext* context, const ::silicon_based::ExtSourceSetRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::silicon_based::ParamResponse, ::silicon_based::ExtSourceSetRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_SetExtSource_, context, request);
}

::grpc::ClientAsyncResponseReader< ::silicon_based::ParamResponse>* LNAWGCMDService::Stub::AsyncSetExtSourceRaw(::grpc::ClientContext* context, const ::silicon_based::ExtSourceSetRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncSetExtSourceRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status LNAWGCMDService::Stub::GetExtSource(::grpc::ClientContext* context, const ::silicon_based::ExtSourceGetRequest& request, ::silicon_based::ExtSourceGetResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::silicon_based::ExtSourceGetRequest, ::silicon_based::ExtSourceGetResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_GetExtSource_, context, request, response);
}

void LNAWGCMDService::Stub::async::GetExtSource(::grpc::ClientContext* context, const ::silicon_based::ExtSourceGetRequest* request, ::silicon_based::ExtSourceGetResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::silicon_based::ExtSourceGetRequest, ::silicon_based::ExtSourceGetResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_GetExtSource_, context, request, response, std::move(f));
}

void LNAWGCMDService::Stub::async::GetExtSource(::grpc::ClientContext* context, const ::silicon_based::ExtSourceGetRequest* request, ::silicon_based::ExtSourceGetResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_GetExtSource_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::silicon_based::ExtSourceGetResponse>* LNAWGCMDService::Stub::PrepareAsyncGetExtSourceRaw(::grpc::ClientContext* context, const ::silicon_based::ExtSourceGetRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::silicon_based::ExtSourceGetResponse, ::silicon_based::ExtSourceGetRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_GetExtSource_, context, request);
}

::grpc::ClientAsyncResponseReader< ::silicon_based::ExtSourceGetResponse>* LNAWGCMDService::Stub::AsyncGetExtSourceRaw(::grpc::ClientContext* context, const ::silicon_based::ExtSourceGetRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncGetExtSourceRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status LNAWGCMDService::Stub::SetRange(::grpc::ClientContext* context, const ::silicon_based::RangeSetRequest& request, ::silicon_based::ParamResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::silicon_based::RangeSetRequest, ::silicon_based::ParamResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_SetRange_, context, request, response);
}

void LNAWGCMDService::Stub::async::SetRange(::grpc::ClientContext* context, const ::silicon_based::RangeSetRequest* request, ::silicon_based::ParamResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::silicon_based::RangeSetRequest, ::silicon_based::ParamResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_SetRange_, context, request, response, std::move(f));
}

void LNAWGCMDService::Stub::async::SetRange(::grpc::ClientContext* context, const ::silicon_based::RangeSetRequest* request, ::silicon_based::ParamResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_SetRange_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::silicon_based::ParamResponse>* LNAWGCMDService::Stub::PrepareAsyncSetRangeRaw(::grpc::ClientContext* context, const ::silicon_based::RangeSetRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::silicon_based::ParamResponse, ::silicon_based::RangeSetRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_SetRange_, context, request);
}

::grpc::ClientAsyncResponseReader< ::silicon_based::ParamResponse>* LNAWGCMDService::Stub::AsyncSetRangeRaw(::grpc::ClientContext* context, const ::silicon_based::RangeSetRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncSetRangeRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status LNAWGCMDService::Stub::GetRange(::grpc::ClientContext* context, const ::silicon_based::RangeGetRequest& request, ::silicon_based::RangeGetResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::silicon_based::RangeGetRequest, ::silicon_based::RangeGetResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_GetRange_, context, request, response);
}

void LNAWGCMDService::Stub::async::GetRange(::grpc::ClientContext* context, const ::silicon_based::RangeGetRequest* request, ::silicon_based::RangeGetResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::silicon_based::RangeGetRequest, ::silicon_based::RangeGetResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_GetRange_, context, request, response, std::move(f));
}

void LNAWGCMDService::Stub::async::GetRange(::grpc::ClientContext* context, const ::silicon_based::RangeGetRequest* request, ::silicon_based::RangeGetResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_GetRange_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::silicon_based::RangeGetResponse>* LNAWGCMDService::Stub::PrepareAsyncGetRangeRaw(::grpc::ClientContext* context, const ::silicon_based::RangeGetRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::silicon_based::RangeGetResponse, ::silicon_based::RangeGetRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_GetRange_, context, request);
}

::grpc::ClientAsyncResponseReader< ::silicon_based::RangeGetResponse>* LNAWGCMDService::Stub::AsyncGetRangeRaw(::grpc::ClientContext* context, const ::silicon_based::RangeGetRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncGetRangeRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status LNAWGCMDService::Stub::SetOffset(::grpc::ClientContext* context, const ::silicon_based::OffsetSetRequest& request, ::silicon_based::ParamResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::silicon_based::OffsetSetRequest, ::silicon_based::ParamResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_SetOffset_, context, request, response);
}

void LNAWGCMDService::Stub::async::SetOffset(::grpc::ClientContext* context, const ::silicon_based::OffsetSetRequest* request, ::silicon_based::ParamResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::silicon_based::OffsetSetRequest, ::silicon_based::ParamResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_SetOffset_, context, request, response, std::move(f));
}

void LNAWGCMDService::Stub::async::SetOffset(::grpc::ClientContext* context, const ::silicon_based::OffsetSetRequest* request, ::silicon_based::ParamResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_SetOffset_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::silicon_based::ParamResponse>* LNAWGCMDService::Stub::PrepareAsyncSetOffsetRaw(::grpc::ClientContext* context, const ::silicon_based::OffsetSetRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::silicon_based::ParamResponse, ::silicon_based::OffsetSetRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_SetOffset_, context, request);
}

::grpc::ClientAsyncResponseReader< ::silicon_based::ParamResponse>* LNAWGCMDService::Stub::AsyncSetOffsetRaw(::grpc::ClientContext* context, const ::silicon_based::OffsetSetRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncSetOffsetRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status LNAWGCMDService::Stub::GetOffset(::grpc::ClientContext* context, const ::silicon_based::OffsetGetRequest& request, ::silicon_based::OffsetGetResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::silicon_based::OffsetGetRequest, ::silicon_based::OffsetGetResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_GetOffset_, context, request, response);
}

void LNAWGCMDService::Stub::async::GetOffset(::grpc::ClientContext* context, const ::silicon_based::OffsetGetRequest* request, ::silicon_based::OffsetGetResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::silicon_based::OffsetGetRequest, ::silicon_based::OffsetGetResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_GetOffset_, context, request, response, std::move(f));
}

void LNAWGCMDService::Stub::async::GetOffset(::grpc::ClientContext* context, const ::silicon_based::OffsetGetRequest* request, ::silicon_based::OffsetGetResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_GetOffset_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::silicon_based::OffsetGetResponse>* LNAWGCMDService::Stub::PrepareAsyncGetOffsetRaw(::grpc::ClientContext* context, const ::silicon_based::OffsetGetRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::silicon_based::OffsetGetResponse, ::silicon_based::OffsetGetRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_GetOffset_, context, request);
}

::grpc::ClientAsyncResponseReader< ::silicon_based::OffsetGetResponse>* LNAWGCMDService::Stub::AsyncGetOffsetRaw(::grpc::ClientContext* context, const ::silicon_based::OffsetGetRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncGetOffsetRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status LNAWGCMDService::Stub::SetSegmentCount(::grpc::ClientContext* context, const ::silicon_based::SegmentCountSetRequest& request, ::silicon_based::ParamResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::silicon_based::SegmentCountSetRequest, ::silicon_based::ParamResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_SetSegmentCount_, context, request, response);
}

void LNAWGCMDService::Stub::async::SetSegmentCount(::grpc::ClientContext* context, const ::silicon_based::SegmentCountSetRequest* request, ::silicon_based::ParamResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::silicon_based::SegmentCountSetRequest, ::silicon_based::ParamResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_SetSegmentCount_, context, request, response, std::move(f));
}

void LNAWGCMDService::Stub::async::SetSegmentCount(::grpc::ClientContext* context, const ::silicon_based::SegmentCountSetRequest* request, ::silicon_based::ParamResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_SetSegmentCount_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::silicon_based::ParamResponse>* LNAWGCMDService::Stub::PrepareAsyncSetSegmentCountRaw(::grpc::ClientContext* context, const ::silicon_based::SegmentCountSetRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::silicon_based::ParamResponse, ::silicon_based::SegmentCountSetRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_SetSegmentCount_, context, request);
}

::grpc::ClientAsyncResponseReader< ::silicon_based::ParamResponse>* LNAWGCMDService::Stub::AsyncSetSegmentCountRaw(::grpc::ClientContext* context, const ::silicon_based::SegmentCountSetRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncSetSegmentCountRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status LNAWGCMDService::Stub::GetSegmentCount(::grpc::ClientContext* context, const ::silicon_based::SegmentCountGetRequest& request, ::silicon_based::SegmentCountGetResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::silicon_based::SegmentCountGetRequest, ::silicon_based::SegmentCountGetResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_GetSegmentCount_, context, request, response);
}

void LNAWGCMDService::Stub::async::GetSegmentCount(::grpc::ClientContext* context, const ::silicon_based::SegmentCountGetRequest* request, ::silicon_based::SegmentCountGetResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::silicon_based::SegmentCountGetRequest, ::silicon_based::SegmentCountGetResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_GetSegmentCount_, context, request, response, std::move(f));
}

void LNAWGCMDService::Stub::async::GetSegmentCount(::grpc::ClientContext* context, const ::silicon_based::SegmentCountGetRequest* request, ::silicon_based::SegmentCountGetResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_GetSegmentCount_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::silicon_based::SegmentCountGetResponse>* LNAWGCMDService::Stub::PrepareAsyncGetSegmentCountRaw(::grpc::ClientContext* context, const ::silicon_based::SegmentCountGetRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::silicon_based::SegmentCountGetResponse, ::silicon_based::SegmentCountGetRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_GetSegmentCount_, context, request);
}

::grpc::ClientAsyncResponseReader< ::silicon_based::SegmentCountGetResponse>* LNAWGCMDService::Stub::AsyncGetSegmentCountRaw(::grpc::ClientContext* context, const ::silicon_based::SegmentCountGetRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncGetSegmentCountRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status LNAWGCMDService::Stub::SetLoopCount(::grpc::ClientContext* context, const ::silicon_based::LoopCountSetRequest& request, ::silicon_based::ParamResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::silicon_based::LoopCountSetRequest, ::silicon_based::ParamResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_SetLoopCount_, context, request, response);
}

void LNAWGCMDService::Stub::async::SetLoopCount(::grpc::ClientContext* context, const ::silicon_based::LoopCountSetRequest* request, ::silicon_based::ParamResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::silicon_based::LoopCountSetRequest, ::silicon_based::ParamResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_SetLoopCount_, context, request, response, std::move(f));
}

void LNAWGCMDService::Stub::async::SetLoopCount(::grpc::ClientContext* context, const ::silicon_based::LoopCountSetRequest* request, ::silicon_based::ParamResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_SetLoopCount_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::silicon_based::ParamResponse>* LNAWGCMDService::Stub::PrepareAsyncSetLoopCountRaw(::grpc::ClientContext* context, const ::silicon_based::LoopCountSetRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::silicon_based::ParamResponse, ::silicon_based::LoopCountSetRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_SetLoopCount_, context, request);
}

::grpc::ClientAsyncResponseReader< ::silicon_based::ParamResponse>* LNAWGCMDService::Stub::AsyncSetLoopCountRaw(::grpc::ClientContext* context, const ::silicon_based::LoopCountSetRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncSetLoopCountRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status LNAWGCMDService::Stub::GetLoopCount(::grpc::ClientContext* context, const ::silicon_based::LoopCountGetRequest& request, ::silicon_based::LoopCountGetResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::silicon_based::LoopCountGetRequest, ::silicon_based::LoopCountGetResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_GetLoopCount_, context, request, response);
}

void LNAWGCMDService::Stub::async::GetLoopCount(::grpc::ClientContext* context, const ::silicon_based::LoopCountGetRequest* request, ::silicon_based::LoopCountGetResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::silicon_based::LoopCountGetRequest, ::silicon_based::LoopCountGetResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_GetLoopCount_, context, request, response, std::move(f));
}

void LNAWGCMDService::Stub::async::GetLoopCount(::grpc::ClientContext* context, const ::silicon_based::LoopCountGetRequest* request, ::silicon_based::LoopCountGetResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_GetLoopCount_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::silicon_based::LoopCountGetResponse>* LNAWGCMDService::Stub::PrepareAsyncGetLoopCountRaw(::grpc::ClientContext* context, const ::silicon_based::LoopCountGetRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::silicon_based::LoopCountGetResponse, ::silicon_based::LoopCountGetRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_GetLoopCount_, context, request);
}

::grpc::ClientAsyncResponseReader< ::silicon_based::LoopCountGetResponse>* LNAWGCMDService::Stub::AsyncGetLoopCountRaw(::grpc::ClientContext* context, const ::silicon_based::LoopCountGetRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncGetLoopCountRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status LNAWGCMDService::Stub::SetDDSParam(::grpc::ClientContext* context, const ::silicon_based::DDSParamSetRequest& request, ::silicon_based::ParamResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::silicon_based::DDSParamSetRequest, ::silicon_based::ParamResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_SetDDSParam_, context, request, response);
}

void LNAWGCMDService::Stub::async::SetDDSParam(::grpc::ClientContext* context, const ::silicon_based::DDSParamSetRequest* request, ::silicon_based::ParamResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::silicon_based::DDSParamSetRequest, ::silicon_based::ParamResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_SetDDSParam_, context, request, response, std::move(f));
}

void LNAWGCMDService::Stub::async::SetDDSParam(::grpc::ClientContext* context, const ::silicon_based::DDSParamSetRequest* request, ::silicon_based::ParamResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_SetDDSParam_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::silicon_based::ParamResponse>* LNAWGCMDService::Stub::PrepareAsyncSetDDSParamRaw(::grpc::ClientContext* context, const ::silicon_based::DDSParamSetRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::silicon_based::ParamResponse, ::silicon_based::DDSParamSetRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_SetDDSParam_, context, request);
}

::grpc::ClientAsyncResponseReader< ::silicon_based::ParamResponse>* LNAWGCMDService::Stub::AsyncSetDDSParamRaw(::grpc::ClientContext* context, const ::silicon_based::DDSParamSetRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncSetDDSParamRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status LNAWGCMDService::Stub::GetDDSParam(::grpc::ClientContext* context, const ::silicon_based::DDSParamGetRequest& request, ::silicon_based::DDSParamGetResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::silicon_based::DDSParamGetRequest, ::silicon_based::DDSParamGetResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_GetDDSParam_, context, request, response);
}

void LNAWGCMDService::Stub::async::GetDDSParam(::grpc::ClientContext* context, const ::silicon_based::DDSParamGetRequest* request, ::silicon_based::DDSParamGetResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::silicon_based::DDSParamGetRequest, ::silicon_based::DDSParamGetResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_GetDDSParam_, context, request, response, std::move(f));
}

void LNAWGCMDService::Stub::async::GetDDSParam(::grpc::ClientContext* context, const ::silicon_based::DDSParamGetRequest* request, ::silicon_based::DDSParamGetResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_GetDDSParam_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::silicon_based::DDSParamGetResponse>* LNAWGCMDService::Stub::PrepareAsyncGetDDSParamRaw(::grpc::ClientContext* context, const ::silicon_based::DDSParamGetRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::silicon_based::DDSParamGetResponse, ::silicon_based::DDSParamGetRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_GetDDSParam_, context, request);
}

::grpc::ClientAsyncResponseReader< ::silicon_based::DDSParamGetResponse>* LNAWGCMDService::Stub::AsyncGetDDSParamRaw(::grpc::ClientContext* context, const ::silicon_based::DDSParamGetRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncGetDDSParamRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status LNAWGCMDService::Stub::SetChirpOutParam(::grpc::ClientContext* context, const ::silicon_based::ChirpOutParamSetRequest& request, ::silicon_based::ParamResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::silicon_based::ChirpOutParamSetRequest, ::silicon_based::ParamResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_SetChirpOutParam_, context, request, response);
}

void LNAWGCMDService::Stub::async::SetChirpOutParam(::grpc::ClientContext* context, const ::silicon_based::ChirpOutParamSetRequest* request, ::silicon_based::ParamResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::silicon_based::ChirpOutParamSetRequest, ::silicon_based::ParamResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_SetChirpOutParam_, context, request, response, std::move(f));
}

void LNAWGCMDService::Stub::async::SetChirpOutParam(::grpc::ClientContext* context, const ::silicon_based::ChirpOutParamSetRequest* request, ::silicon_based::ParamResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_SetChirpOutParam_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::silicon_based::ParamResponse>* LNAWGCMDService::Stub::PrepareAsyncSetChirpOutParamRaw(::grpc::ClientContext* context, const ::silicon_based::ChirpOutParamSetRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::silicon_based::ParamResponse, ::silicon_based::ChirpOutParamSetRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_SetChirpOutParam_, context, request);
}

::grpc::ClientAsyncResponseReader< ::silicon_based::ParamResponse>* LNAWGCMDService::Stub::AsyncSetChirpOutParamRaw(::grpc::ClientContext* context, const ::silicon_based::ChirpOutParamSetRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncSetChirpOutParamRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status LNAWGCMDService::Stub::GetChirpOutParam(::grpc::ClientContext* context, const ::silicon_based::ChirpOutParamGetRequest& request, ::silicon_based::ChirpOutParamGetResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::silicon_based::ChirpOutParamGetRequest, ::silicon_based::ChirpOutParamGetResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_GetChirpOutParam_, context, request, response);
}

void LNAWGCMDService::Stub::async::GetChirpOutParam(::grpc::ClientContext* context, const ::silicon_based::ChirpOutParamGetRequest* request, ::silicon_based::ChirpOutParamGetResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::silicon_based::ChirpOutParamGetRequest, ::silicon_based::ChirpOutParamGetResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_GetChirpOutParam_, context, request, response, std::move(f));
}

void LNAWGCMDService::Stub::async::GetChirpOutParam(::grpc::ClientContext* context, const ::silicon_based::ChirpOutParamGetRequest* request, ::silicon_based::ChirpOutParamGetResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_GetChirpOutParam_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::silicon_based::ChirpOutParamGetResponse>* LNAWGCMDService::Stub::PrepareAsyncGetChirpOutParamRaw(::grpc::ClientContext* context, const ::silicon_based::ChirpOutParamGetRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::silicon_based::ChirpOutParamGetResponse, ::silicon_based::ChirpOutParamGetRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_GetChirpOutParam_, context, request);
}

::grpc::ClientAsyncResponseReader< ::silicon_based::ChirpOutParamGetResponse>* LNAWGCMDService::Stub::AsyncGetChirpOutParamRaw(::grpc::ClientContext* context, const ::silicon_based::ChirpOutParamGetRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncGetChirpOutParamRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status LNAWGCMDService::Stub::SetDDSEnable(::grpc::ClientContext* context, const ::silicon_based::DDSEnableSetRequest& request, ::silicon_based::ParamResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::silicon_based::DDSEnableSetRequest, ::silicon_based::ParamResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_SetDDSEnable_, context, request, response);
}

void LNAWGCMDService::Stub::async::SetDDSEnable(::grpc::ClientContext* context, const ::silicon_based::DDSEnableSetRequest* request, ::silicon_based::ParamResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::silicon_based::DDSEnableSetRequest, ::silicon_based::ParamResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_SetDDSEnable_, context, request, response, std::move(f));
}

void LNAWGCMDService::Stub::async::SetDDSEnable(::grpc::ClientContext* context, const ::silicon_based::DDSEnableSetRequest* request, ::silicon_based::ParamResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_SetDDSEnable_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::silicon_based::ParamResponse>* LNAWGCMDService::Stub::PrepareAsyncSetDDSEnableRaw(::grpc::ClientContext* context, const ::silicon_based::DDSEnableSetRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::silicon_based::ParamResponse, ::silicon_based::DDSEnableSetRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_SetDDSEnable_, context, request);
}

::grpc::ClientAsyncResponseReader< ::silicon_based::ParamResponse>* LNAWGCMDService::Stub::AsyncSetDDSEnableRaw(::grpc::ClientContext* context, const ::silicon_based::DDSEnableSetRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncSetDDSEnableRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status LNAWGCMDService::Stub::GetDDSEnable(::grpc::ClientContext* context, const ::silicon_based::DDSEnableGetRequest& request, ::silicon_based::DDSEnableGetResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::silicon_based::DDSEnableGetRequest, ::silicon_based::DDSEnableGetResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_GetDDSEnable_, context, request, response);
}

void LNAWGCMDService::Stub::async::GetDDSEnable(::grpc::ClientContext* context, const ::silicon_based::DDSEnableGetRequest* request, ::silicon_based::DDSEnableGetResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::silicon_based::DDSEnableGetRequest, ::silicon_based::DDSEnableGetResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_GetDDSEnable_, context, request, response, std::move(f));
}

void LNAWGCMDService::Stub::async::GetDDSEnable(::grpc::ClientContext* context, const ::silicon_based::DDSEnableGetRequest* request, ::silicon_based::DDSEnableGetResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_GetDDSEnable_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::silicon_based::DDSEnableGetResponse>* LNAWGCMDService::Stub::PrepareAsyncGetDDSEnableRaw(::grpc::ClientContext* context, const ::silicon_based::DDSEnableGetRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::silicon_based::DDSEnableGetResponse, ::silicon_based::DDSEnableGetRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_GetDDSEnable_, context, request);
}

::grpc::ClientAsyncResponseReader< ::silicon_based::DDSEnableGetResponse>* LNAWGCMDService::Stub::AsyncGetDDSEnableRaw(::grpc::ClientContext* context, const ::silicon_based::DDSEnableGetRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncGetDDSEnableRaw(context, request, cq);
  result->StartCall();
  return result;
}

LNAWGCMDService::Service::Service() {
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      LNAWGCMDService_method_names[0],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< LNAWGCMDService::Service, ::silicon_based::ModeSetRequest, ::silicon_based::ParamResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](LNAWGCMDService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::silicon_based::ModeSetRequest* req,
             ::silicon_based::ParamResponse* resp) {
               return service->SetMode(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      LNAWGCMDService_method_names[1],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< LNAWGCMDService::Service, ::silicon_based::ModeGetRequest, ::silicon_based::ModeGetResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](LNAWGCMDService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::silicon_based::ModeGetRequest* req,
             ::silicon_based::ModeGetResponse* resp) {
               return service->GetMode(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      LNAWGCMDService_method_names[2],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< LNAWGCMDService::Service, ::silicon_based::RunSetRequest, ::silicon_based::ParamResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](LNAWGCMDService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::silicon_based::RunSetRequest* req,
             ::silicon_based::ParamResponse* resp) {
               return service->SetRun(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      LNAWGCMDService_method_names[3],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< LNAWGCMDService::Service, ::silicon_based::RunGetRequest, ::silicon_based::RunGetResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](LNAWGCMDService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::silicon_based::RunGetRequest* req,
             ::silicon_based::RunGetResponse* resp) {
               return service->GetRun(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      LNAWGCMDService_method_names[4],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< LNAWGCMDService::Service, ::silicon_based::ExtSourceSetRequest, ::silicon_based::ParamResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](LNAWGCMDService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::silicon_based::ExtSourceSetRequest* req,
             ::silicon_based::ParamResponse* resp) {
               return service->SetExtSource(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      LNAWGCMDService_method_names[5],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< LNAWGCMDService::Service, ::silicon_based::ExtSourceGetRequest, ::silicon_based::ExtSourceGetResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](LNAWGCMDService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::silicon_based::ExtSourceGetRequest* req,
             ::silicon_based::ExtSourceGetResponse* resp) {
               return service->GetExtSource(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      LNAWGCMDService_method_names[6],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< LNAWGCMDService::Service, ::silicon_based::RangeSetRequest, ::silicon_based::ParamResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](LNAWGCMDService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::silicon_based::RangeSetRequest* req,
             ::silicon_based::ParamResponse* resp) {
               return service->SetRange(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      LNAWGCMDService_method_names[7],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< LNAWGCMDService::Service, ::silicon_based::RangeGetRequest, ::silicon_based::RangeGetResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](LNAWGCMDService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::silicon_based::RangeGetRequest* req,
             ::silicon_based::RangeGetResponse* resp) {
               return service->GetRange(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      LNAWGCMDService_method_names[8],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< LNAWGCMDService::Service, ::silicon_based::OffsetSetRequest, ::silicon_based::ParamResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](LNAWGCMDService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::silicon_based::OffsetSetRequest* req,
             ::silicon_based::ParamResponse* resp) {
               return service->SetOffset(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      LNAWGCMDService_method_names[9],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< LNAWGCMDService::Service, ::silicon_based::OffsetGetRequest, ::silicon_based::OffsetGetResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](LNAWGCMDService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::silicon_based::OffsetGetRequest* req,
             ::silicon_based::OffsetGetResponse* resp) {
               return service->GetOffset(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      LNAWGCMDService_method_names[10],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< LNAWGCMDService::Service, ::silicon_based::SegmentCountSetRequest, ::silicon_based::ParamResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](LNAWGCMDService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::silicon_based::SegmentCountSetRequest* req,
             ::silicon_based::ParamResponse* resp) {
               return service->SetSegmentCount(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      LNAWGCMDService_method_names[11],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< LNAWGCMDService::Service, ::silicon_based::SegmentCountGetRequest, ::silicon_based::SegmentCountGetResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](LNAWGCMDService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::silicon_based::SegmentCountGetRequest* req,
             ::silicon_based::SegmentCountGetResponse* resp) {
               return service->GetSegmentCount(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      LNAWGCMDService_method_names[12],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< LNAWGCMDService::Service, ::silicon_based::LoopCountSetRequest, ::silicon_based::ParamResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](LNAWGCMDService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::silicon_based::LoopCountSetRequest* req,
             ::silicon_based::ParamResponse* resp) {
               return service->SetLoopCount(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      LNAWGCMDService_method_names[13],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< LNAWGCMDService::Service, ::silicon_based::LoopCountGetRequest, ::silicon_based::LoopCountGetResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](LNAWGCMDService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::silicon_based::LoopCountGetRequest* req,
             ::silicon_based::LoopCountGetResponse* resp) {
               return service->GetLoopCount(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      LNAWGCMDService_method_names[14],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< LNAWGCMDService::Service, ::silicon_based::DDSParamSetRequest, ::silicon_based::ParamResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](LNAWGCMDService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::silicon_based::DDSParamSetRequest* req,
             ::silicon_based::ParamResponse* resp) {
               return service->SetDDSParam(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      LNAWGCMDService_method_names[15],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< LNAWGCMDService::Service, ::silicon_based::DDSParamGetRequest, ::silicon_based::DDSParamGetResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](LNAWGCMDService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::silicon_based::DDSParamGetRequest* req,
             ::silicon_based::DDSParamGetResponse* resp) {
               return service->GetDDSParam(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      LNAWGCMDService_method_names[16],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< LNAWGCMDService::Service, ::silicon_based::ChirpOutParamSetRequest, ::silicon_based::ParamResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](LNAWGCMDService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::silicon_based::ChirpOutParamSetRequest* req,
             ::silicon_based::ParamResponse* resp) {
               return service->SetChirpOutParam(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      LNAWGCMDService_method_names[17],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< LNAWGCMDService::Service, ::silicon_based::ChirpOutParamGetRequest, ::silicon_based::ChirpOutParamGetResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](LNAWGCMDService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::silicon_based::ChirpOutParamGetRequest* req,
             ::silicon_based::ChirpOutParamGetResponse* resp) {
               return service->GetChirpOutParam(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      LNAWGCMDService_method_names[18],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< LNAWGCMDService::Service, ::silicon_based::DDSEnableSetRequest, ::silicon_based::ParamResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](LNAWGCMDService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::silicon_based::DDSEnableSetRequest* req,
             ::silicon_based::ParamResponse* resp) {
               return service->SetDDSEnable(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      LNAWGCMDService_method_names[19],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< LNAWGCMDService::Service, ::silicon_based::DDSEnableGetRequest, ::silicon_based::DDSEnableGetResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](LNAWGCMDService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::silicon_based::DDSEnableGetRequest* req,
             ::silicon_based::DDSEnableGetResponse* resp) {
               return service->GetDDSEnable(ctx, req, resp);
             }, this)));
}

LNAWGCMDService::Service::~Service() {
}

::grpc::Status LNAWGCMDService::Service::SetMode(::grpc::ServerContext* context, const ::silicon_based::ModeSetRequest* request, ::silicon_based::ParamResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status LNAWGCMDService::Service::GetMode(::grpc::ServerContext* context, const ::silicon_based::ModeGetRequest* request, ::silicon_based::ModeGetResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status LNAWGCMDService::Service::SetRun(::grpc::ServerContext* context, const ::silicon_based::RunSetRequest* request, ::silicon_based::ParamResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status LNAWGCMDService::Service::GetRun(::grpc::ServerContext* context, const ::silicon_based::RunGetRequest* request, ::silicon_based::RunGetResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status LNAWGCMDService::Service::SetExtSource(::grpc::ServerContext* context, const ::silicon_based::ExtSourceSetRequest* request, ::silicon_based::ParamResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status LNAWGCMDService::Service::GetExtSource(::grpc::ServerContext* context, const ::silicon_based::ExtSourceGetRequest* request, ::silicon_based::ExtSourceGetResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status LNAWGCMDService::Service::SetRange(::grpc::ServerContext* context, const ::silicon_based::RangeSetRequest* request, ::silicon_based::ParamResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status LNAWGCMDService::Service::GetRange(::grpc::ServerContext* context, const ::silicon_based::RangeGetRequest* request, ::silicon_based::RangeGetResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status LNAWGCMDService::Service::SetOffset(::grpc::ServerContext* context, const ::silicon_based::OffsetSetRequest* request, ::silicon_based::ParamResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status LNAWGCMDService::Service::GetOffset(::grpc::ServerContext* context, const ::silicon_based::OffsetGetRequest* request, ::silicon_based::OffsetGetResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status LNAWGCMDService::Service::SetSegmentCount(::grpc::ServerContext* context, const ::silicon_based::SegmentCountSetRequest* request, ::silicon_based::ParamResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status LNAWGCMDService::Service::GetSegmentCount(::grpc::ServerContext* context, const ::silicon_based::SegmentCountGetRequest* request, ::silicon_based::SegmentCountGetResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status LNAWGCMDService::Service::SetLoopCount(::grpc::ServerContext* context, const ::silicon_based::LoopCountSetRequest* request, ::silicon_based::ParamResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status LNAWGCMDService::Service::GetLoopCount(::grpc::ServerContext* context, const ::silicon_based::LoopCountGetRequest* request, ::silicon_based::LoopCountGetResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status LNAWGCMDService::Service::SetDDSParam(::grpc::ServerContext* context, const ::silicon_based::DDSParamSetRequest* request, ::silicon_based::ParamResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status LNAWGCMDService::Service::GetDDSParam(::grpc::ServerContext* context, const ::silicon_based::DDSParamGetRequest* request, ::silicon_based::DDSParamGetResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status LNAWGCMDService::Service::SetChirpOutParam(::grpc::ServerContext* context, const ::silicon_based::ChirpOutParamSetRequest* request, ::silicon_based::ParamResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status LNAWGCMDService::Service::GetChirpOutParam(::grpc::ServerContext* context, const ::silicon_based::ChirpOutParamGetRequest* request, ::silicon_based::ChirpOutParamGetResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status LNAWGCMDService::Service::SetDDSEnable(::grpc::ServerContext* context, const ::silicon_based::DDSEnableSetRequest* request, ::silicon_based::ParamResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status LNAWGCMDService::Service::GetDDSEnable(::grpc::ServerContext* context, const ::silicon_based::DDSEnableGetRequest* request, ::silicon_based::DDSEnableGetResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}


}  // namespace silicon_based

