// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: qa_cmd.proto

#include "qa_cmd.pb.h"
#include "qa_cmd.grpc.pb.h"

#include <functional>
#include <grpcpp/support/async_stream.h>
#include <grpcpp/support/async_unary_call.h>
#include <grpcpp/impl/channel_interface.h>
#include <grpcpp/impl/client_unary_call.h>
#include <grpcpp/support/client_callback.h>
#include <grpcpp/support/message_allocator.h>
#include <grpcpp/support/method_handler.h>
#include <grpcpp/impl/rpc_service_method.h>
#include <grpcpp/support/server_callback.h>
#include <grpcpp/impl/server_callback_handlers.h>
#include <grpcpp/server_context.h>
#include <grpcpp/impl/service_type.h>
#include <grpcpp/support/sync_stream.h>
namespace silicon_based {

static const char* QACMDService_method_names[] = {
  "/silicon_based.QACMDService/SetTrigSour",
  "/silicon_based.QACMDService/SetSoftTrig",
  "/silicon_based.QACMDService/SetDACDDSConfig",
  "/silicon_based.QACMDService/GetDACDDSConfig",
  "/silicon_based.QACMDService/SetDACPlayParam",
  "/silicon_based.QACMDService/GetDACPlayParam",
  "/silicon_based.QACMDService/SetDACStartStop",
  "/silicon_based.QACMDService/GetDACStartStop",
  "/silicon_based.QACMDService/SetSampleParam",
  "/silicon_based.QACMDService/GetSampleParam",
  "/silicon_based.QACMDService/SetSampleStartStop",
  "/silicon_based.QACMDService/GetSampleStartStop",
  "/silicon_based.QACMDService/SetADCConfig",
  "/silicon_based.QACMDService/GetADCConfig",
  "/silicon_based.QACMDService/SetADCPlayParam",
  "/silicon_based.QACMDService/GetADCPlayParam",
  "/silicon_based.QACMDService/SetADCStartStop",
  "/silicon_based.QACMDService/GetADCStartStop",
};

std::unique_ptr< QACMDService::Stub> QACMDService::NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options) {
  (void)options;
  std::unique_ptr< QACMDService::Stub> stub(new QACMDService::Stub(channel, options));
  return stub;
}

QACMDService::Stub::Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options)
  : channel_(channel), rpcmethod_SetTrigSour_(QACMDService_method_names[0], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_SetSoftTrig_(QACMDService_method_names[1], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_SetDACDDSConfig_(QACMDService_method_names[2], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_GetDACDDSConfig_(QACMDService_method_names[3], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_SetDACPlayParam_(QACMDService_method_names[4], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_GetDACPlayParam_(QACMDService_method_names[5], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_SetDACStartStop_(QACMDService_method_names[6], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_GetDACStartStop_(QACMDService_method_names[7], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_SetSampleParam_(QACMDService_method_names[8], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_GetSampleParam_(QACMDService_method_names[9], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_SetSampleStartStop_(QACMDService_method_names[10], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_GetSampleStartStop_(QACMDService_method_names[11], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_SetADCConfig_(QACMDService_method_names[12], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_GetADCConfig_(QACMDService_method_names[13], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_SetADCPlayParam_(QACMDService_method_names[14], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_GetADCPlayParam_(QACMDService_method_names[15], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_SetADCStartStop_(QACMDService_method_names[16], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_GetADCStartStop_(QACMDService_method_names[17], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  {}

::grpc::Status QACMDService::Stub::SetTrigSour(::grpc::ClientContext* context, const ::silicon_based::SetTrigSourRequest& request, ::silicon_based::ParamResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::silicon_based::SetTrigSourRequest, ::silicon_based::ParamResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_SetTrigSour_, context, request, response);
}

void QACMDService::Stub::async::SetTrigSour(::grpc::ClientContext* context, const ::silicon_based::SetTrigSourRequest* request, ::silicon_based::ParamResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::silicon_based::SetTrigSourRequest, ::silicon_based::ParamResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_SetTrigSour_, context, request, response, std::move(f));
}

void QACMDService::Stub::async::SetTrigSour(::grpc::ClientContext* context, const ::silicon_based::SetTrigSourRequest* request, ::silicon_based::ParamResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_SetTrigSour_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::silicon_based::ParamResponse>* QACMDService::Stub::PrepareAsyncSetTrigSourRaw(::grpc::ClientContext* context, const ::silicon_based::SetTrigSourRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::silicon_based::ParamResponse, ::silicon_based::SetTrigSourRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_SetTrigSour_, context, request);
}

::grpc::ClientAsyncResponseReader< ::silicon_based::ParamResponse>* QACMDService::Stub::AsyncSetTrigSourRaw(::grpc::ClientContext* context, const ::silicon_based::SetTrigSourRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncSetTrigSourRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status QACMDService::Stub::SetSoftTrig(::grpc::ClientContext* context, const ::silicon_based::SetSoftTrigRequest& request, ::silicon_based::ParamResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::silicon_based::SetSoftTrigRequest, ::silicon_based::ParamResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_SetSoftTrig_, context, request, response);
}

void QACMDService::Stub::async::SetSoftTrig(::grpc::ClientContext* context, const ::silicon_based::SetSoftTrigRequest* request, ::silicon_based::ParamResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::silicon_based::SetSoftTrigRequest, ::silicon_based::ParamResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_SetSoftTrig_, context, request, response, std::move(f));
}

void QACMDService::Stub::async::SetSoftTrig(::grpc::ClientContext* context, const ::silicon_based::SetSoftTrigRequest* request, ::silicon_based::ParamResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_SetSoftTrig_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::silicon_based::ParamResponse>* QACMDService::Stub::PrepareAsyncSetSoftTrigRaw(::grpc::ClientContext* context, const ::silicon_based::SetSoftTrigRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::silicon_based::ParamResponse, ::silicon_based::SetSoftTrigRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_SetSoftTrig_, context, request);
}

::grpc::ClientAsyncResponseReader< ::silicon_based::ParamResponse>* QACMDService::Stub::AsyncSetSoftTrigRaw(::grpc::ClientContext* context, const ::silicon_based::SetSoftTrigRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncSetSoftTrigRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status QACMDService::Stub::SetDACDDSConfig(::grpc::ClientContext* context, const ::silicon_based::SetDACDDSConfigRequest& request, ::silicon_based::ParamResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::silicon_based::SetDACDDSConfigRequest, ::silicon_based::ParamResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_SetDACDDSConfig_, context, request, response);
}

void QACMDService::Stub::async::SetDACDDSConfig(::grpc::ClientContext* context, const ::silicon_based::SetDACDDSConfigRequest* request, ::silicon_based::ParamResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::silicon_based::SetDACDDSConfigRequest, ::silicon_based::ParamResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_SetDACDDSConfig_, context, request, response, std::move(f));
}

void QACMDService::Stub::async::SetDACDDSConfig(::grpc::ClientContext* context, const ::silicon_based::SetDACDDSConfigRequest* request, ::silicon_based::ParamResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_SetDACDDSConfig_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::silicon_based::ParamResponse>* QACMDService::Stub::PrepareAsyncSetDACDDSConfigRaw(::grpc::ClientContext* context, const ::silicon_based::SetDACDDSConfigRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::silicon_based::ParamResponse, ::silicon_based::SetDACDDSConfigRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_SetDACDDSConfig_, context, request);
}

::grpc::ClientAsyncResponseReader< ::silicon_based::ParamResponse>* QACMDService::Stub::AsyncSetDACDDSConfigRaw(::grpc::ClientContext* context, const ::silicon_based::SetDACDDSConfigRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncSetDACDDSConfigRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status QACMDService::Stub::GetDACDDSConfig(::grpc::ClientContext* context, const ::silicon_based::GetDACDDSConfigRequest& request, ::silicon_based::GetDACDDSConfigResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::silicon_based::GetDACDDSConfigRequest, ::silicon_based::GetDACDDSConfigResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_GetDACDDSConfig_, context, request, response);
}

void QACMDService::Stub::async::GetDACDDSConfig(::grpc::ClientContext* context, const ::silicon_based::GetDACDDSConfigRequest* request, ::silicon_based::GetDACDDSConfigResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::silicon_based::GetDACDDSConfigRequest, ::silicon_based::GetDACDDSConfigResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_GetDACDDSConfig_, context, request, response, std::move(f));
}

void QACMDService::Stub::async::GetDACDDSConfig(::grpc::ClientContext* context, const ::silicon_based::GetDACDDSConfigRequest* request, ::silicon_based::GetDACDDSConfigResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_GetDACDDSConfig_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::silicon_based::GetDACDDSConfigResponse>* QACMDService::Stub::PrepareAsyncGetDACDDSConfigRaw(::grpc::ClientContext* context, const ::silicon_based::GetDACDDSConfigRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::silicon_based::GetDACDDSConfigResponse, ::silicon_based::GetDACDDSConfigRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_GetDACDDSConfig_, context, request);
}

::grpc::ClientAsyncResponseReader< ::silicon_based::GetDACDDSConfigResponse>* QACMDService::Stub::AsyncGetDACDDSConfigRaw(::grpc::ClientContext* context, const ::silicon_based::GetDACDDSConfigRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncGetDACDDSConfigRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status QACMDService::Stub::SetDACPlayParam(::grpc::ClientContext* context, const ::silicon_based::SetDACPlayParamRequest& request, ::silicon_based::ParamResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::silicon_based::SetDACPlayParamRequest, ::silicon_based::ParamResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_SetDACPlayParam_, context, request, response);
}

void QACMDService::Stub::async::SetDACPlayParam(::grpc::ClientContext* context, const ::silicon_based::SetDACPlayParamRequest* request, ::silicon_based::ParamResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::silicon_based::SetDACPlayParamRequest, ::silicon_based::ParamResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_SetDACPlayParam_, context, request, response, std::move(f));
}

void QACMDService::Stub::async::SetDACPlayParam(::grpc::ClientContext* context, const ::silicon_based::SetDACPlayParamRequest* request, ::silicon_based::ParamResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_SetDACPlayParam_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::silicon_based::ParamResponse>* QACMDService::Stub::PrepareAsyncSetDACPlayParamRaw(::grpc::ClientContext* context, const ::silicon_based::SetDACPlayParamRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::silicon_based::ParamResponse, ::silicon_based::SetDACPlayParamRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_SetDACPlayParam_, context, request);
}

::grpc::ClientAsyncResponseReader< ::silicon_based::ParamResponse>* QACMDService::Stub::AsyncSetDACPlayParamRaw(::grpc::ClientContext* context, const ::silicon_based::SetDACPlayParamRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncSetDACPlayParamRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status QACMDService::Stub::GetDACPlayParam(::grpc::ClientContext* context, const ::silicon_based::GetDACPlayParamRequest& request, ::silicon_based::GetDACPlayParamResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::silicon_based::GetDACPlayParamRequest, ::silicon_based::GetDACPlayParamResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_GetDACPlayParam_, context, request, response);
}

void QACMDService::Stub::async::GetDACPlayParam(::grpc::ClientContext* context, const ::silicon_based::GetDACPlayParamRequest* request, ::silicon_based::GetDACPlayParamResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::silicon_based::GetDACPlayParamRequest, ::silicon_based::GetDACPlayParamResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_GetDACPlayParam_, context, request, response, std::move(f));
}

void QACMDService::Stub::async::GetDACPlayParam(::grpc::ClientContext* context, const ::silicon_based::GetDACPlayParamRequest* request, ::silicon_based::GetDACPlayParamResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_GetDACPlayParam_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::silicon_based::GetDACPlayParamResponse>* QACMDService::Stub::PrepareAsyncGetDACPlayParamRaw(::grpc::ClientContext* context, const ::silicon_based::GetDACPlayParamRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::silicon_based::GetDACPlayParamResponse, ::silicon_based::GetDACPlayParamRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_GetDACPlayParam_, context, request);
}

::grpc::ClientAsyncResponseReader< ::silicon_based::GetDACPlayParamResponse>* QACMDService::Stub::AsyncGetDACPlayParamRaw(::grpc::ClientContext* context, const ::silicon_based::GetDACPlayParamRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncGetDACPlayParamRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status QACMDService::Stub::SetDACStartStop(::grpc::ClientContext* context, const ::silicon_based::SetDACStartStopRequest& request, ::silicon_based::ParamResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::silicon_based::SetDACStartStopRequest, ::silicon_based::ParamResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_SetDACStartStop_, context, request, response);
}

void QACMDService::Stub::async::SetDACStartStop(::grpc::ClientContext* context, const ::silicon_based::SetDACStartStopRequest* request, ::silicon_based::ParamResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::silicon_based::SetDACStartStopRequest, ::silicon_based::ParamResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_SetDACStartStop_, context, request, response, std::move(f));
}

void QACMDService::Stub::async::SetDACStartStop(::grpc::ClientContext* context, const ::silicon_based::SetDACStartStopRequest* request, ::silicon_based::ParamResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_SetDACStartStop_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::silicon_based::ParamResponse>* QACMDService::Stub::PrepareAsyncSetDACStartStopRaw(::grpc::ClientContext* context, const ::silicon_based::SetDACStartStopRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::silicon_based::ParamResponse, ::silicon_based::SetDACStartStopRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_SetDACStartStop_, context, request);
}

::grpc::ClientAsyncResponseReader< ::silicon_based::ParamResponse>* QACMDService::Stub::AsyncSetDACStartStopRaw(::grpc::ClientContext* context, const ::silicon_based::SetDACStartStopRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncSetDACStartStopRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status QACMDService::Stub::GetDACStartStop(::grpc::ClientContext* context, const ::silicon_based::GetDACStartStopRequest& request, ::silicon_based::GetDACStartStopResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::silicon_based::GetDACStartStopRequest, ::silicon_based::GetDACStartStopResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_GetDACStartStop_, context, request, response);
}

void QACMDService::Stub::async::GetDACStartStop(::grpc::ClientContext* context, const ::silicon_based::GetDACStartStopRequest* request, ::silicon_based::GetDACStartStopResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::silicon_based::GetDACStartStopRequest, ::silicon_based::GetDACStartStopResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_GetDACStartStop_, context, request, response, std::move(f));
}

void QACMDService::Stub::async::GetDACStartStop(::grpc::ClientContext* context, const ::silicon_based::GetDACStartStopRequest* request, ::silicon_based::GetDACStartStopResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_GetDACStartStop_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::silicon_based::GetDACStartStopResponse>* QACMDService::Stub::PrepareAsyncGetDACStartStopRaw(::grpc::ClientContext* context, const ::silicon_based::GetDACStartStopRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::silicon_based::GetDACStartStopResponse, ::silicon_based::GetDACStartStopRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_GetDACStartStop_, context, request);
}

::grpc::ClientAsyncResponseReader< ::silicon_based::GetDACStartStopResponse>* QACMDService::Stub::AsyncGetDACStartStopRaw(::grpc::ClientContext* context, const ::silicon_based::GetDACStartStopRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncGetDACStartStopRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status QACMDService::Stub::SetSampleParam(::grpc::ClientContext* context, const ::silicon_based::SetSampleParamRequest& request, ::silicon_based::ParamResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::silicon_based::SetSampleParamRequest, ::silicon_based::ParamResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_SetSampleParam_, context, request, response);
}

void QACMDService::Stub::async::SetSampleParam(::grpc::ClientContext* context, const ::silicon_based::SetSampleParamRequest* request, ::silicon_based::ParamResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::silicon_based::SetSampleParamRequest, ::silicon_based::ParamResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_SetSampleParam_, context, request, response, std::move(f));
}

void QACMDService::Stub::async::SetSampleParam(::grpc::ClientContext* context, const ::silicon_based::SetSampleParamRequest* request, ::silicon_based::ParamResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_SetSampleParam_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::silicon_based::ParamResponse>* QACMDService::Stub::PrepareAsyncSetSampleParamRaw(::grpc::ClientContext* context, const ::silicon_based::SetSampleParamRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::silicon_based::ParamResponse, ::silicon_based::SetSampleParamRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_SetSampleParam_, context, request);
}

::grpc::ClientAsyncResponseReader< ::silicon_based::ParamResponse>* QACMDService::Stub::AsyncSetSampleParamRaw(::grpc::ClientContext* context, const ::silicon_based::SetSampleParamRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncSetSampleParamRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status QACMDService::Stub::GetSampleParam(::grpc::ClientContext* context, const ::silicon_based::GetSampleParamRequest& request, ::silicon_based::GetSampleParamResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::silicon_based::GetSampleParamRequest, ::silicon_based::GetSampleParamResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_GetSampleParam_, context, request, response);
}

void QACMDService::Stub::async::GetSampleParam(::grpc::ClientContext* context, const ::silicon_based::GetSampleParamRequest* request, ::silicon_based::GetSampleParamResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::silicon_based::GetSampleParamRequest, ::silicon_based::GetSampleParamResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_GetSampleParam_, context, request, response, std::move(f));
}

void QACMDService::Stub::async::GetSampleParam(::grpc::ClientContext* context, const ::silicon_based::GetSampleParamRequest* request, ::silicon_based::GetSampleParamResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_GetSampleParam_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::silicon_based::GetSampleParamResponse>* QACMDService::Stub::PrepareAsyncGetSampleParamRaw(::grpc::ClientContext* context, const ::silicon_based::GetSampleParamRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::silicon_based::GetSampleParamResponse, ::silicon_based::GetSampleParamRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_GetSampleParam_, context, request);
}

::grpc::ClientAsyncResponseReader< ::silicon_based::GetSampleParamResponse>* QACMDService::Stub::AsyncGetSampleParamRaw(::grpc::ClientContext* context, const ::silicon_based::GetSampleParamRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncGetSampleParamRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status QACMDService::Stub::SetSampleStartStop(::grpc::ClientContext* context, const ::silicon_based::SetSampleStartStopRequest& request, ::silicon_based::ParamResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::silicon_based::SetSampleStartStopRequest, ::silicon_based::ParamResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_SetSampleStartStop_, context, request, response);
}

void QACMDService::Stub::async::SetSampleStartStop(::grpc::ClientContext* context, const ::silicon_based::SetSampleStartStopRequest* request, ::silicon_based::ParamResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::silicon_based::SetSampleStartStopRequest, ::silicon_based::ParamResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_SetSampleStartStop_, context, request, response, std::move(f));
}

void QACMDService::Stub::async::SetSampleStartStop(::grpc::ClientContext* context, const ::silicon_based::SetSampleStartStopRequest* request, ::silicon_based::ParamResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_SetSampleStartStop_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::silicon_based::ParamResponse>* QACMDService::Stub::PrepareAsyncSetSampleStartStopRaw(::grpc::ClientContext* context, const ::silicon_based::SetSampleStartStopRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::silicon_based::ParamResponse, ::silicon_based::SetSampleStartStopRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_SetSampleStartStop_, context, request);
}

::grpc::ClientAsyncResponseReader< ::silicon_based::ParamResponse>* QACMDService::Stub::AsyncSetSampleStartStopRaw(::grpc::ClientContext* context, const ::silicon_based::SetSampleStartStopRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncSetSampleStartStopRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status QACMDService::Stub::GetSampleStartStop(::grpc::ClientContext* context, const ::silicon_based::GetSampleStartStopRequest& request, ::silicon_based::GetSampleStartStopResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::silicon_based::GetSampleStartStopRequest, ::silicon_based::GetSampleStartStopResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_GetSampleStartStop_, context, request, response);
}

void QACMDService::Stub::async::GetSampleStartStop(::grpc::ClientContext* context, const ::silicon_based::GetSampleStartStopRequest* request, ::silicon_based::GetSampleStartStopResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::silicon_based::GetSampleStartStopRequest, ::silicon_based::GetSampleStartStopResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_GetSampleStartStop_, context, request, response, std::move(f));
}

void QACMDService::Stub::async::GetSampleStartStop(::grpc::ClientContext* context, const ::silicon_based::GetSampleStartStopRequest* request, ::silicon_based::GetSampleStartStopResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_GetSampleStartStop_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::silicon_based::GetSampleStartStopResponse>* QACMDService::Stub::PrepareAsyncGetSampleStartStopRaw(::grpc::ClientContext* context, const ::silicon_based::GetSampleStartStopRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::silicon_based::GetSampleStartStopResponse, ::silicon_based::GetSampleStartStopRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_GetSampleStartStop_, context, request);
}

::grpc::ClientAsyncResponseReader< ::silicon_based::GetSampleStartStopResponse>* QACMDService::Stub::AsyncGetSampleStartStopRaw(::grpc::ClientContext* context, const ::silicon_based::GetSampleStartStopRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncGetSampleStartStopRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status QACMDService::Stub::SetADCConfig(::grpc::ClientContext* context, const ::silicon_based::SetADCConfigRequest& request, ::silicon_based::ParamResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::silicon_based::SetADCConfigRequest, ::silicon_based::ParamResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_SetADCConfig_, context, request, response);
}

void QACMDService::Stub::async::SetADCConfig(::grpc::ClientContext* context, const ::silicon_based::SetADCConfigRequest* request, ::silicon_based::ParamResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::silicon_based::SetADCConfigRequest, ::silicon_based::ParamResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_SetADCConfig_, context, request, response, std::move(f));
}

void QACMDService::Stub::async::SetADCConfig(::grpc::ClientContext* context, const ::silicon_based::SetADCConfigRequest* request, ::silicon_based::ParamResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_SetADCConfig_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::silicon_based::ParamResponse>* QACMDService::Stub::PrepareAsyncSetADCConfigRaw(::grpc::ClientContext* context, const ::silicon_based::SetADCConfigRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::silicon_based::ParamResponse, ::silicon_based::SetADCConfigRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_SetADCConfig_, context, request);
}

::grpc::ClientAsyncResponseReader< ::silicon_based::ParamResponse>* QACMDService::Stub::AsyncSetADCConfigRaw(::grpc::ClientContext* context, const ::silicon_based::SetADCConfigRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncSetADCConfigRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status QACMDService::Stub::GetADCConfig(::grpc::ClientContext* context, const ::silicon_based::GetADCConfigRequest& request, ::silicon_based::GetADCConfigResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::silicon_based::GetADCConfigRequest, ::silicon_based::GetADCConfigResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_GetADCConfig_, context, request, response);
}

void QACMDService::Stub::async::GetADCConfig(::grpc::ClientContext* context, const ::silicon_based::GetADCConfigRequest* request, ::silicon_based::GetADCConfigResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::silicon_based::GetADCConfigRequest, ::silicon_based::GetADCConfigResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_GetADCConfig_, context, request, response, std::move(f));
}

void QACMDService::Stub::async::GetADCConfig(::grpc::ClientContext* context, const ::silicon_based::GetADCConfigRequest* request, ::silicon_based::GetADCConfigResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_GetADCConfig_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::silicon_based::GetADCConfigResponse>* QACMDService::Stub::PrepareAsyncGetADCConfigRaw(::grpc::ClientContext* context, const ::silicon_based::GetADCConfigRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::silicon_based::GetADCConfigResponse, ::silicon_based::GetADCConfigRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_GetADCConfig_, context, request);
}

::grpc::ClientAsyncResponseReader< ::silicon_based::GetADCConfigResponse>* QACMDService::Stub::AsyncGetADCConfigRaw(::grpc::ClientContext* context, const ::silicon_based::GetADCConfigRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncGetADCConfigRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status QACMDService::Stub::SetADCPlayParam(::grpc::ClientContext* context, const ::silicon_based::SetADCPlayParamRequest& request, ::silicon_based::ParamResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::silicon_based::SetADCPlayParamRequest, ::silicon_based::ParamResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_SetADCPlayParam_, context, request, response);
}

void QACMDService::Stub::async::SetADCPlayParam(::grpc::ClientContext* context, const ::silicon_based::SetADCPlayParamRequest* request, ::silicon_based::ParamResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::silicon_based::SetADCPlayParamRequest, ::silicon_based::ParamResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_SetADCPlayParam_, context, request, response, std::move(f));
}

void QACMDService::Stub::async::SetADCPlayParam(::grpc::ClientContext* context, const ::silicon_based::SetADCPlayParamRequest* request, ::silicon_based::ParamResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_SetADCPlayParam_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::silicon_based::ParamResponse>* QACMDService::Stub::PrepareAsyncSetADCPlayParamRaw(::grpc::ClientContext* context, const ::silicon_based::SetADCPlayParamRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::silicon_based::ParamResponse, ::silicon_based::SetADCPlayParamRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_SetADCPlayParam_, context, request);
}

::grpc::ClientAsyncResponseReader< ::silicon_based::ParamResponse>* QACMDService::Stub::AsyncSetADCPlayParamRaw(::grpc::ClientContext* context, const ::silicon_based::SetADCPlayParamRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncSetADCPlayParamRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status QACMDService::Stub::GetADCPlayParam(::grpc::ClientContext* context, const ::silicon_based::GetADCPlayParamRequest& request, ::silicon_based::GetADCPlayParamResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::silicon_based::GetADCPlayParamRequest, ::silicon_based::GetADCPlayParamResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_GetADCPlayParam_, context, request, response);
}

void QACMDService::Stub::async::GetADCPlayParam(::grpc::ClientContext* context, const ::silicon_based::GetADCPlayParamRequest* request, ::silicon_based::GetADCPlayParamResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::silicon_based::GetADCPlayParamRequest, ::silicon_based::GetADCPlayParamResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_GetADCPlayParam_, context, request, response, std::move(f));
}

void QACMDService::Stub::async::GetADCPlayParam(::grpc::ClientContext* context, const ::silicon_based::GetADCPlayParamRequest* request, ::silicon_based::GetADCPlayParamResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_GetADCPlayParam_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::silicon_based::GetADCPlayParamResponse>* QACMDService::Stub::PrepareAsyncGetADCPlayParamRaw(::grpc::ClientContext* context, const ::silicon_based::GetADCPlayParamRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::silicon_based::GetADCPlayParamResponse, ::silicon_based::GetADCPlayParamRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_GetADCPlayParam_, context, request);
}

::grpc::ClientAsyncResponseReader< ::silicon_based::GetADCPlayParamResponse>* QACMDService::Stub::AsyncGetADCPlayParamRaw(::grpc::ClientContext* context, const ::silicon_based::GetADCPlayParamRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncGetADCPlayParamRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status QACMDService::Stub::SetADCStartStop(::grpc::ClientContext* context, const ::silicon_based::SetADCStartStopRequest& request, ::silicon_based::ParamResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::silicon_based::SetADCStartStopRequest, ::silicon_based::ParamResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_SetADCStartStop_, context, request, response);
}

void QACMDService::Stub::async::SetADCStartStop(::grpc::ClientContext* context, const ::silicon_based::SetADCStartStopRequest* request, ::silicon_based::ParamResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::silicon_based::SetADCStartStopRequest, ::silicon_based::ParamResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_SetADCStartStop_, context, request, response, std::move(f));
}

void QACMDService::Stub::async::SetADCStartStop(::grpc::ClientContext* context, const ::silicon_based::SetADCStartStopRequest* request, ::silicon_based::ParamResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_SetADCStartStop_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::silicon_based::ParamResponse>* QACMDService::Stub::PrepareAsyncSetADCStartStopRaw(::grpc::ClientContext* context, const ::silicon_based::SetADCStartStopRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::silicon_based::ParamResponse, ::silicon_based::SetADCStartStopRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_SetADCStartStop_, context, request);
}

::grpc::ClientAsyncResponseReader< ::silicon_based::ParamResponse>* QACMDService::Stub::AsyncSetADCStartStopRaw(::grpc::ClientContext* context, const ::silicon_based::SetADCStartStopRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncSetADCStartStopRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status QACMDService::Stub::GetADCStartStop(::grpc::ClientContext* context, const ::silicon_based::GetADCStartStopRequest& request, ::silicon_based::GetADCStartStopResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::silicon_based::GetADCStartStopRequest, ::silicon_based::GetADCStartStopResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_GetADCStartStop_, context, request, response);
}

void QACMDService::Stub::async::GetADCStartStop(::grpc::ClientContext* context, const ::silicon_based::GetADCStartStopRequest* request, ::silicon_based::GetADCStartStopResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::silicon_based::GetADCStartStopRequest, ::silicon_based::GetADCStartStopResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_GetADCStartStop_, context, request, response, std::move(f));
}

void QACMDService::Stub::async::GetADCStartStop(::grpc::ClientContext* context, const ::silicon_based::GetADCStartStopRequest* request, ::silicon_based::GetADCStartStopResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_GetADCStartStop_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::silicon_based::GetADCStartStopResponse>* QACMDService::Stub::PrepareAsyncGetADCStartStopRaw(::grpc::ClientContext* context, const ::silicon_based::GetADCStartStopRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::silicon_based::GetADCStartStopResponse, ::silicon_based::GetADCStartStopRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_GetADCStartStop_, context, request);
}

::grpc::ClientAsyncResponseReader< ::silicon_based::GetADCStartStopResponse>* QACMDService::Stub::AsyncGetADCStartStopRaw(::grpc::ClientContext* context, const ::silicon_based::GetADCStartStopRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncGetADCStartStopRaw(context, request, cq);
  result->StartCall();
  return result;
}

QACMDService::Service::Service() {
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      QACMDService_method_names[0],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< QACMDService::Service, ::silicon_based::SetTrigSourRequest, ::silicon_based::ParamResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](QACMDService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::silicon_based::SetTrigSourRequest* req,
             ::silicon_based::ParamResponse* resp) {
               return service->SetTrigSour(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      QACMDService_method_names[1],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< QACMDService::Service, ::silicon_based::SetSoftTrigRequest, ::silicon_based::ParamResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](QACMDService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::silicon_based::SetSoftTrigRequest* req,
             ::silicon_based::ParamResponse* resp) {
               return service->SetSoftTrig(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      QACMDService_method_names[2],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< QACMDService::Service, ::silicon_based::SetDACDDSConfigRequest, ::silicon_based::ParamResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](QACMDService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::silicon_based::SetDACDDSConfigRequest* req,
             ::silicon_based::ParamResponse* resp) {
               return service->SetDACDDSConfig(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      QACMDService_method_names[3],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< QACMDService::Service, ::silicon_based::GetDACDDSConfigRequest, ::silicon_based::GetDACDDSConfigResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](QACMDService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::silicon_based::GetDACDDSConfigRequest* req,
             ::silicon_based::GetDACDDSConfigResponse* resp) {
               return service->GetDACDDSConfig(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      QACMDService_method_names[4],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< QACMDService::Service, ::silicon_based::SetDACPlayParamRequest, ::silicon_based::ParamResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](QACMDService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::silicon_based::SetDACPlayParamRequest* req,
             ::silicon_based::ParamResponse* resp) {
               return service->SetDACPlayParam(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      QACMDService_method_names[5],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< QACMDService::Service, ::silicon_based::GetDACPlayParamRequest, ::silicon_based::GetDACPlayParamResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](QACMDService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::silicon_based::GetDACPlayParamRequest* req,
             ::silicon_based::GetDACPlayParamResponse* resp) {
               return service->GetDACPlayParam(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      QACMDService_method_names[6],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< QACMDService::Service, ::silicon_based::SetDACStartStopRequest, ::silicon_based::ParamResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](QACMDService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::silicon_based::SetDACStartStopRequest* req,
             ::silicon_based::ParamResponse* resp) {
               return service->SetDACStartStop(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      QACMDService_method_names[7],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< QACMDService::Service, ::silicon_based::GetDACStartStopRequest, ::silicon_based::GetDACStartStopResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](QACMDService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::silicon_based::GetDACStartStopRequest* req,
             ::silicon_based::GetDACStartStopResponse* resp) {
               return service->GetDACStartStop(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      QACMDService_method_names[8],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< QACMDService::Service, ::silicon_based::SetSampleParamRequest, ::silicon_based::ParamResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](QACMDService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::silicon_based::SetSampleParamRequest* req,
             ::silicon_based::ParamResponse* resp) {
               return service->SetSampleParam(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      QACMDService_method_names[9],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< QACMDService::Service, ::silicon_based::GetSampleParamRequest, ::silicon_based::GetSampleParamResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](QACMDService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::silicon_based::GetSampleParamRequest* req,
             ::silicon_based::GetSampleParamResponse* resp) {
               return service->GetSampleParam(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      QACMDService_method_names[10],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< QACMDService::Service, ::silicon_based::SetSampleStartStopRequest, ::silicon_based::ParamResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](QACMDService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::silicon_based::SetSampleStartStopRequest* req,
             ::silicon_based::ParamResponse* resp) {
               return service->SetSampleStartStop(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      QACMDService_method_names[11],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< QACMDService::Service, ::silicon_based::GetSampleStartStopRequest, ::silicon_based::GetSampleStartStopResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](QACMDService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::silicon_based::GetSampleStartStopRequest* req,
             ::silicon_based::GetSampleStartStopResponse* resp) {
               return service->GetSampleStartStop(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      QACMDService_method_names[12],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< QACMDService::Service, ::silicon_based::SetADCConfigRequest, ::silicon_based::ParamResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](QACMDService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::silicon_based::SetADCConfigRequest* req,
             ::silicon_based::ParamResponse* resp) {
               return service->SetADCConfig(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      QACMDService_method_names[13],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< QACMDService::Service, ::silicon_based::GetADCConfigRequest, ::silicon_based::GetADCConfigResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](QACMDService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::silicon_based::GetADCConfigRequest* req,
             ::silicon_based::GetADCConfigResponse* resp) {
               return service->GetADCConfig(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      QACMDService_method_names[14],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< QACMDService::Service, ::silicon_based::SetADCPlayParamRequest, ::silicon_based::ParamResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](QACMDService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::silicon_based::SetADCPlayParamRequest* req,
             ::silicon_based::ParamResponse* resp) {
               return service->SetADCPlayParam(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      QACMDService_method_names[15],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< QACMDService::Service, ::silicon_based::GetADCPlayParamRequest, ::silicon_based::GetADCPlayParamResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](QACMDService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::silicon_based::GetADCPlayParamRequest* req,
             ::silicon_based::GetADCPlayParamResponse* resp) {
               return service->GetADCPlayParam(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      QACMDService_method_names[16],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< QACMDService::Service, ::silicon_based::SetADCStartStopRequest, ::silicon_based::ParamResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](QACMDService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::silicon_based::SetADCStartStopRequest* req,
             ::silicon_based::ParamResponse* resp) {
               return service->SetADCStartStop(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      QACMDService_method_names[17],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< QACMDService::Service, ::silicon_based::GetADCStartStopRequest, ::silicon_based::GetADCStartStopResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](QACMDService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::silicon_based::GetADCStartStopRequest* req,
             ::silicon_based::GetADCStartStopResponse* resp) {
               return service->GetADCStartStop(ctx, req, resp);
             }, this)));
}

QACMDService::Service::~Service() {
}

::grpc::Status QACMDService::Service::SetTrigSour(::grpc::ServerContext* context, const ::silicon_based::SetTrigSourRequest* request, ::silicon_based::ParamResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status QACMDService::Service::SetSoftTrig(::grpc::ServerContext* context, const ::silicon_based::SetSoftTrigRequest* request, ::silicon_based::ParamResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status QACMDService::Service::SetDACDDSConfig(::grpc::ServerContext* context, const ::silicon_based::SetDACDDSConfigRequest* request, ::silicon_based::ParamResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status QACMDService::Service::GetDACDDSConfig(::grpc::ServerContext* context, const ::silicon_based::GetDACDDSConfigRequest* request, ::silicon_based::GetDACDDSConfigResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status QACMDService::Service::SetDACPlayParam(::grpc::ServerContext* context, const ::silicon_based::SetDACPlayParamRequest* request, ::silicon_based::ParamResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status QACMDService::Service::GetDACPlayParam(::grpc::ServerContext* context, const ::silicon_based::GetDACPlayParamRequest* request, ::silicon_based::GetDACPlayParamResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status QACMDService::Service::SetDACStartStop(::grpc::ServerContext* context, const ::silicon_based::SetDACStartStopRequest* request, ::silicon_based::ParamResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status QACMDService::Service::GetDACStartStop(::grpc::ServerContext* context, const ::silicon_based::GetDACStartStopRequest* request, ::silicon_based::GetDACStartStopResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status QACMDService::Service::SetSampleParam(::grpc::ServerContext* context, const ::silicon_based::SetSampleParamRequest* request, ::silicon_based::ParamResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status QACMDService::Service::GetSampleParam(::grpc::ServerContext* context, const ::silicon_based::GetSampleParamRequest* request, ::silicon_based::GetSampleParamResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status QACMDService::Service::SetSampleStartStop(::grpc::ServerContext* context, const ::silicon_based::SetSampleStartStopRequest* request, ::silicon_based::ParamResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status QACMDService::Service::GetSampleStartStop(::grpc::ServerContext* context, const ::silicon_based::GetSampleStartStopRequest* request, ::silicon_based::GetSampleStartStopResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status QACMDService::Service::SetADCConfig(::grpc::ServerContext* context, const ::silicon_based::SetADCConfigRequest* request, ::silicon_based::ParamResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status QACMDService::Service::GetADCConfig(::grpc::ServerContext* context, const ::silicon_based::GetADCConfigRequest* request, ::silicon_based::GetADCConfigResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status QACMDService::Service::SetADCPlayParam(::grpc::ServerContext* context, const ::silicon_based::SetADCPlayParamRequest* request, ::silicon_based::ParamResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status QACMDService::Service::GetADCPlayParam(::grpc::ServerContext* context, const ::silicon_based::GetADCPlayParamRequest* request, ::silicon_based::GetADCPlayParamResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status QACMDService::Service::SetADCStartStop(::grpc::ServerContext* context, const ::silicon_based::SetADCStartStopRequest* request, ::silicon_based::ParamResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status QACMDService::Service::GetADCStartStop(::grpc::ServerContext* context, const ::silicon_based::GetADCStartStopRequest* request, ::silicon_based::GetADCStartStopResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}


}  // namespace silicon_based

